import { createCardStructureFrom, getJsCard, isCardTypeFile } from '../../../cardtype/base.js';
import { playCancelSound, playConfirmSound, playHoverSound, setTempSoundDisable } from '../../sound.js';

class CardTypeWizard extends HTMLElement {
    constructor() {
        super();
        this.root = this.attachShadow({ mode: 'open' });
        this.onDocumentKeydown = this.onDocumentKeydown.bind(this);
        /** @type {number | null} */
        this._overlayTimer = null;
        /** @type {number | null} */
        this._autosaveHideTimer = null;
    }

    connectedCallback() {
        this.render();

        document.addEventListener('keydown', this.onDocumentKeydown);

        this.root.getElementById('cancel-btn')?.addEventListener('click', () => {
            playCancelSound();
            setTempSoundDisable();
            this.remove();
        });

        this.root.querySelectorAll('.wizard-buttons div').forEach(btn => {
            btn.addEventListener('mouseenter', playHoverSound);
        });

        this.initializeCard();
    }

    async initializeCard() {
        const characterId = this.getAttribute('character-id');
        const characterNamespace = this.getAttribute('character-namespace');
        if (!characterId || !characterNamespace) {
            console.error('CardTypeWizard requires character-id and character-namespace attributes');
            return;
        }
        const cardSource = await window.ENGINE_WORKER_CLIENT.getRawScriptSource({ namespace: characterNamespace, id: characterId });
        console.log('Card source:', cardSource);
        const isCardType = isCardTypeFile(cardSource.src);

        if (!isCardType) {
            const contentArea = this.root.querySelector('.wizard-content');
            // @ts-ignore
            contentArea.innerHTML = `<p>This character script was not generated by the character wizard, so it can only be edited manually.</p>`;
        } else {
            const parsedCard = createCardStructureFrom(cardSource.src);
            const isCompleteCard = parsedCard.config.guidedWizardCompleted || parsedCard.config.automaticWizardCompleted;
            if (isCompleteCard) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script has already been completed using the wizard</p>`;
                return;
            }

            let isAutomaticInProgress = parsedCard.config.automaticWizardInProgress && !parsedCard.config.automaticWizardCompleted;
            let isGuidedInProgress = parsedCard.config.guidedWizardInProgress && !parsedCard.config.guidedWizardCompleted;

            const isNewFile = cardSource.src.startsWith("//@placeholder");

            if (isNewFile) {
                // new file check the options
                const wizardExpectation = this.getAttribute('wizard-expectation');
                if (wizardExpectation === 'automatic') {
                    isAutomaticInProgress = true;
                } else if (wizardExpectation === 'guided') {
                    isGuidedInProgress = true;
                }
            }

            if (isAutomaticInProgress || isGuidedInProgress) {
                const titleName = isAutomaticInProgress ? 'Automatic Wizard' : 'Guided Wizard';
                const titleText = this.root.querySelector('.wizard-title span:first-child');
                if (titleText) {
                    titleText.textContent = titleName;
                }

                if (isAutomaticInProgress) {
                    this.startMode(parsedCard, 'automatic', isNewFile);
                } else {
                    this.startMode(parsedCard, 'guided', isNewFile);
                }
            } else {
                const contentArea = this.root.querySelector('.wizard-content');
                // unknown state, should not happen, say that it's probably another version of the wizard and not this one
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script is in an unknown state. It may have been generated by an older/newer version of the wizard, or there may be an issue with the script. Please edit the script manually or try regenerating it with the latest version of the wizard.</p>`;
            }
        }
    }

    /**
     * @param {import('../../../cardtype/base.js').CardTypeCard} parsedCard 
     * @param {"automatic" | "guided"} mode 
     * @param {boolean} isNewFile
     */
    startMode(parsedCard, mode, isNewFile) {
        if (isNewFile) {
            const contentArea = this.root.querySelector('.wizard-content');
            if (!contentArea) return;

            const buttonLabel = mode === 'automatic' ? 'Automatic Start' : 'Guided Start';

            contentArea.innerHTML = `
                <div class="wizard-card-input">
                    <textarea class="card-textarea" placeholder="Paste your character card here..."></textarea>
                    <div class="wizard-start-btn">${buttonLabel}</div>
                </div>
            `;

            const textarea = contentArea.querySelector('.card-textarea');
            if (textarea) {
                textarea.addEventListener('input', function() {
                    // @ts-ignore
                    this.style.height = 'auto';
                    // @ts-ignore
                    this.style.height = this.scrollHeight + 'px';
                });
            }

            const startBtn = contentArea.querySelector('.wizard-start-btn');
            if (startBtn) {
                startBtn.addEventListener('mouseenter', playHoverSound);
                startBtn.addEventListener('click', () => {
                    playConfirmSound();
                    // @ts-ignore
                    const cardText = (textarea?.value || '').trim();
                    if (!cardText) {
                        return;
                    }
                    parsedCard.card = cardText;
                    if (mode === 'automatic') {
                        parsedCard.config.automaticWizardInProgress = false;
                        parsedCard.config.automaticWizardCompleted = true;
                    } else {
                        parsedCard.config.guidedWizardInProgress = false;
                        parsedCard.config.guidedWizardCompleted = true;
                    }
                    this.continueProcess(parsedCard, mode);
                });
            }
        } else {
            this.continueProcess(parsedCard, mode);
        }
    }

    /**
     * @param {import('../../../cardtype/base.js').CardTypeCard} parsedCard 
     * @param {"automatic" | "guided"} mode
     */
    async continueProcess(parsedCard, mode) {
        /** @type {import('../../../cardtype/base.js').CardTypeGuider | null} */
        const guider = mode === 'guided' ? this.createUIGuider() : null;

        const autosave = {
            save: async () => {

                if (!parsedCard) return;
                const jsContent = getJsCard(parsedCard);
                this.showAutosaveStatus();
                await window.API.updateScriptFile(parsedCard.config.namespace, parsedCard.config.id, jsContent);
                this.hideAutosaveStatus();
            }
        }

        if (guider) {
            const wait = () => new Promise(r => setTimeout(r, 5000));
            
            // Dummy questions to test each type
            const optionResult = await guider.askOption('What is the character archetype?', ['Hero', 'Villain', 'Anti-Hero', 'Mentor', 'Trickster'], 'Hero');
            console.log('askOption result:', optionResult);
            await wait();

            const openResult = await guider.askOpen('Describe the character in a few words', 'A brave adventurer');
            console.log('askOpen result:', openResult);
            await wait();

            const numberResult = await guider.askNumber('How old is the character?', 25);
            console.log('askNumber result:', numberResult);
            await wait();

            const booleanResult = await guider.askBoolean('Is the character a leader?', true);
            console.log('askBoolean result:', booleanResult);
            await wait();

            const listResult = await guider.askList('What are the character\'s hobbies?', ['Reading', 'Swordfighting']);
            console.log('askList result:', listResult);
        }
    }

    /**
     * Creates a UI-based guider that renders interactive questions into the wizard content area.
     * Each method returns a promise that resolves when the user submits their answer.
     * @returns {import('../../../cardtype/base.js').CardTypeGuider}
     */
    createUIGuider() {
        const self = this;

        /**
         * Renders a question into the content area and returns a promise.
         * @param {string} question
         * @param {() => HTMLElement} buildInputFn - builds the input element(s)
         * @param {(container: HTMLElement) => any} extractValueFn - extracts the value on submit
         * @param {any} [defaultValue]
         * @returns {Promise<{value: any}>}
         */
        function presentQuestion(question, buildInputFn, extractValueFn, defaultValue) {
            return new Promise((resolve) => {
                self.endOverlay();

                const contentArea = self.root.querySelector('.wizard-content');
                if (!contentArea) { resolve({ value: defaultValue }); return; }

                contentArea.innerHTML = '';

                const container = document.createElement('div');
                container.className = 'guider-question';

                const questionLabel = document.createElement('div');
                questionLabel.className = 'guider-label';
                questionLabel.textContent = question;
                container.appendChild(questionLabel);

                const inputArea = buildInputFn();
                container.appendChild(inputArea);

                const submitBtn = document.createElement('div');
                submitBtn.className = 'guider-submit-btn';
                submitBtn.textContent = 'Confirm';
                submitBtn.addEventListener('mouseenter', playHoverSound);
                submitBtn.addEventListener('click', () => {
                    playConfirmSound();
                    const value = extractValueFn(inputArea);
                    self.initOverlay();
                    resolve({ value });
                });
                container.appendChild(submitBtn);

                contentArea.appendChild(container);
            });
        }

        return {
            async askOption(question, options, defaultValue) {
                return presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-options';
                        options.forEach((opt, i) => {
                            const optBtn = document.createElement('div');
                            optBtn.className = 'guider-option';
                            if (opt === defaultValue) optBtn.classList.add('selected');
                            optBtn.textContent = opt;
                            optBtn.addEventListener('mouseenter', playHoverSound);
                            optBtn.addEventListener('click', () => {
                                wrapper.querySelectorAll('.guider-option').forEach(b => b.classList.remove('selected'));
                                optBtn.classList.add('selected');
                            });
                            wrapper.appendChild(optBtn);
                        });
                        return wrapper;
                    },
                    (inputArea) => {
                        const selected = inputArea.querySelector('.guider-option.selected');
                        return selected ? selected.textContent : (defaultValue ?? options[0]);
                    },
                    defaultValue
                );
            },

            async askOpen(question, defaultValue) {
                return presentQuestion(
                    question,
                    () => {
                        const textarea = document.createElement('textarea');
                        textarea.className = 'guider-textarea';
                        textarea.placeholder = defaultValue || '';
                        if (defaultValue) textarea.value = defaultValue;
                        textarea.addEventListener('input', function() {
                            this.style.height = 'auto';
                            this.style.height = this.scrollHeight + 'px';
                        });
                        return textarea;
                    },
                    (inputArea) => {
                        return /** @type {HTMLTextAreaElement} */ (inputArea).value || defaultValue || '';
                    },
                    defaultValue
                );
            },

            async askNumber(question, defaultValue) {
                return presentQuestion(
                    question,
                    () => {
                        const input = document.createElement('input');
                        input.className = 'guider-input';
                        input.type = 'number';
                        if (defaultValue !== undefined) input.value = String(defaultValue);
                        input.placeholder = defaultValue !== undefined ? String(defaultValue) : '0';
                        return input;
                    },
                    (inputArea) => {
                        const num = parseFloat(/** @type {HTMLInputElement} */ (inputArea).value);
                        return isNaN(num) ? (defaultValue ?? 0) : num;
                    },
                    defaultValue
                );
            },

            async askBoolean(question, defaultValue) {
                return presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-boolean';

                        const yesBtn = document.createElement('div');
                        yesBtn.className = 'guider-bool-btn';
                        yesBtn.textContent = 'Yes';
                        if (defaultValue === true) yesBtn.classList.add('selected');

                        const noBtn = document.createElement('div');
                        noBtn.className = 'guider-bool-btn';
                        noBtn.textContent = 'No';
                        if (defaultValue === false) noBtn.classList.add('selected');

                        yesBtn.addEventListener('mouseenter', playHoverSound);
                        noBtn.addEventListener('mouseenter', playHoverSound);

                        yesBtn.addEventListener('click', () => {
                            yesBtn.classList.add('selected');
                            noBtn.classList.remove('selected');
                        });
                        noBtn.addEventListener('click', () => {
                            noBtn.classList.add('selected');
                            yesBtn.classList.remove('selected');
                        });

                        wrapper.appendChild(yesBtn);
                        wrapper.appendChild(noBtn);
                        return wrapper;
                    },
                    (inputArea) => {
                        const yesBtn = inputArea.querySelector('.guider-bool-btn:first-child');
                        return yesBtn?.classList.contains('selected') ?? (defaultValue ?? false);
                    },
                    defaultValue
                );
            },

            async askList(question, defaultValue) {
                return presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-list';

                        /** @type {string[]} */
                        const items = defaultValue ? [...defaultValue] : [];

                        const renderItems = () => {
                            let listContainer = wrapper.querySelector('.guider-list-items');
                            if (!listContainer) {
                                listContainer = document.createElement('div');
                                listContainer.className = 'guider-list-items';
                                wrapper.insertBefore(listContainer, wrapper.querySelector('.guider-list-add-row'));
                            }
                            listContainer.innerHTML = items.map((item, idx) => `
                                <div class="guider-list-item">
                                    <span>${item}</span>
                                    <div class="guider-list-remove" data-idx="${idx}">✕</div>
                                </div>
                            `).join('');
                            listContainer.querySelectorAll('.guider-list-remove').forEach(btn => {
                                btn.addEventListener('mouseenter', playHoverSound);
                                btn.addEventListener('click', () => {
                                    const idx = parseInt(/** @type {HTMLElement} */ (btn).dataset.idx || '0');
                                    items.splice(idx, 1);
                                    renderItems();
                                });
                            });
                        };

                        const addRow = document.createElement('div');
                        addRow.className = 'guider-list-add-row';

                        const addInput = document.createElement('input');
                        addInput.className = 'guider-input';
                        addInput.type = 'text';
                        addInput.placeholder = 'Add item...';

                        const addBtn = document.createElement('div');
                        addBtn.className = 'guider-list-add-btn';
                        addBtn.textContent = '+';
                        addBtn.addEventListener('mouseenter', playHoverSound);
                        addBtn.addEventListener('click', () => {
                            const val = addInput.value.trim();
                            if (!val) return;
                            items.push(val);
                            addInput.value = '';
                            renderItems();
                        });

                        addRow.appendChild(addInput);
                        addRow.appendChild(addBtn);
                        wrapper.appendChild(addRow);

                        renderItems();
                        return wrapper;
                    },
                    (inputArea) => {
                        const itemEls = inputArea.querySelectorAll('.guider-list-item span');
                        const result = Array.from(itemEls).map(el => el.textContent || '');
                        return result.length > 0 ? result : (defaultValue ?? []);
                    },
                    defaultValue
                );
            }
        };
    }

    /**
     * Starts a loading overlay. After 300ms the overlay becomes visible with blur and a spinner.
     * Call endOverlay() to remove it.
     */
    initOverlay() {
        this.endOverlay();

        const overlay = document.createElement('div');
        overlay.className = 'wizard-loading-overlay';
        overlay.innerHTML = '<div class="wizard-spinner"></div><div class="wizard-loading-text">Running inference...</div>';
        this.root.querySelector('.wizard-content')?.appendChild(overlay);

        this._overlayTimer = window.setTimeout(() => {
            overlay.classList.add('visible');
            this._overlayTimer = null;
        }, 300);
    }

    /**
     * Removes the loading overlay immediately, cancelling the 300ms timer if still pending.
     */
    endOverlay() {
        if (this._overlayTimer !== null) {
            clearTimeout(this._overlayTimer);
            this._overlayTimer = null;
        }
        this.root.querySelector('.wizard-loading-overlay')?.remove();
    }

    /**
     * Shows the autosave indicator in the title bar.
     */
    showAutosaveStatus() {
        if (this._autosaveHideTimer) {
            clearTimeout(this._autosaveHideTimer);
            this._autosaveHideTimer = null;
        }
        const el = this.root.querySelector('.wizard-autosave');
        if (el) {
            el.classList.add('visible');
        }
    }

    /**
     * Fades out the autosave indicator after a short delay.
     */
    hideAutosaveStatus() {
        this._autosaveHideTimer = window.setTimeout(() => {
            const el = this.root.querySelector('.wizard-autosave');
            if (el) {
                el.classList.remove('visible');
            }
            this._autosaveHideTimer = null;
        }, 1500);
    }

    disconnectedCallback() {
        this.endOverlay();
        if (this._autosaveHideTimer) {
            clearTimeout(this._autosaveHideTimer);
            this._autosaveHideTimer = null;
        }
        document.removeEventListener('keydown', this.onDocumentKeydown);
    }

    /** @param {KeyboardEvent} e */
    onDocumentKeydown(e) {
        if (e.key === 'Escape') {
            if (document.querySelector('app-dialog')) return;
            const bodyChildren = Array.from(document.body.children);
            if (bodyChildren[bodyChildren.length - 1] !== this) return;
            playCancelSound();
            setTempSoundDisable();
            this.remove();
        }
    }

    render() {
        this.root.innerHTML = `
      <style>
        *::-webkit-scrollbar {
            width: 10px !important;
        }
        *::-webkit-scrollbar-track {
            background: rgba(0, 15, 30, 0.6) !important;
        }
        *::-webkit-scrollbar-thumb {
            background: rgba(0, 60, 90, 0.8) !important;
            border: 1px solid rgba(80, 180, 220, 0.3) !important;
            border-radius: 5px !important;
        }
        *::-webkit-scrollbar-thumb:hover {
            background: rgba(0, 80, 120, 0.9) !important;
        }

        .wizard-overlay {
            position: fixed;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            display: flex;
            justify-content: flex-start;
            flex-direction: column;
            align-items: flex-start;
            background: linear-gradient(
                160deg,
                #000000 0%,
                #000508 6%,
                #000a12 12%,
                #00101a 20%,
                #001420 28%,
                #001825 36%,
                #001a2a 44%,
                #001c2f 52%,
                #001e32 60%,
                #002035 68%,
                #002238 76%,
                #00243b 84%,
                #00263e 92%,
                #002840 100%
            );
            color: #c8dce8;
            z-index: 20;
            box-sizing: border-box;
        }

        .wizard-title {
            font-size: 3vh;
            padding: 2vh 4vh;
            border-bottom: solid 1px rgba(80, 180, 220, 0.25);
            width: 100%;
            background: linear-gradient(
                to right,
                rgba(0, 40, 70, 0.4),
                rgba(0, 20, 40, 0.2)
            );
            box-sizing: border-box;
            letter-spacing: 0.1em;
            text-shadow: 0 0 12px rgba(60, 160, 220, 0.15);
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .wizard-autosave {
            font-size: 2vh;
            color: rgba(100, 200, 240, 0.7);
            opacity: 0;
            transition: opacity 0.4s ease;
            white-space: nowrap;
        }

        .wizard-autosave.visible {
            opacity: 1;
        }

        .wizard-content {
            flex: 1;
            width: 100%;
            padding: 4vh;
            overflow-y: auto;
            box-sizing: border-box;
            position: relative;
        }

        .wizard-buttons {
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            width: 100%;
            padding: 2vh 4vh;
            box-sizing: border-box;
            border-top: solid 1px rgba(80, 180, 220, 0.25);
            background: linear-gradient(
                to right,
                rgba(0, 20, 40, 0.2),
                rgba(0, 40, 70, 0.4)
            );
        }

        .wizard-buttons div {
            font-size: 5vh;
            cursor: pointer;
            color: rgba(120, 200, 240, 0.7);
            transition: color 0.2s ease, text-shadow 0.2s ease;
        }
        .wizard-buttons div:hover {
            color: #60d0ff;
            text-shadow: 0 0 14px rgba(60, 180, 255, 0.4);
        }

        .wizard-card-input {
            padding: 4vh;
            display: flex;
            flex-direction: column;
            gap: 3vh;
        }

        .card-textarea {
            width: 100%;
            min-height: 20vh;
            font-size: 3vh;
            font-family: 'Cabin Sketch', sans-serif;
            font-weight: bold;
            color: #c8dce8;
            background: rgba(0, 10, 20, 0.6);
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            padding: 2vh;
            box-sizing: border-box;
            resize: none;
            overflow: hidden;
            outline: none;
            transition: border-color 0.2s ease, box-shadow 0.2s ease;
            box-shadow: inset 0 0 10px rgba(0, 40, 80, 0.3);
        }

        .card-textarea::placeholder {
            color: rgba(120, 180, 220, 0.35);
        }

        .card-textarea:focus {
            border-color: rgba(80, 180, 220, 0.5);
            box-shadow: inset 0 0 14px rgba(0, 60, 120, 0.4);
        }

        .wizard-start-btn {
            font-size: 4vh;
            cursor: pointer;
            color: rgba(120, 200, 240, 0.7);
            transition: color 0.2s ease, text-shadow 0.2s ease;
            text-align: center;
            padding: 1.5vh 3vh;
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            background: linear-gradient(
                to right,
                rgba(0, 30, 55, 0.4),
                rgba(0, 50, 80, 0.3)
            );
        }

        .wizard-start-btn:hover {
            color: #60d0ff;
            text-shadow: 0 0 14px rgba(60, 180, 255, 0.4);
            border-color: rgba(80, 180, 220, 0.5);
            background: linear-gradient(
                to right,
                rgba(0, 40, 70, 0.5),
                rgba(0, 60, 100, 0.4)
            );
        }

        /* Guider question styles */
        .guider-question {
            display: flex;
            flex-direction: column;
            gap: 2.5vh;
        }

        .guider-label {
            font-size: 3vh;
            color: #c8dce8;
            letter-spacing: 0.03em;
            text-shadow: 0 0 8px rgba(60, 160, 220, 0.1);
        }

        .guider-submit-btn {
            font-size: 3.5vh;
            cursor: pointer;
            color: rgba(120, 200, 240, 0.7);
            transition: color 0.2s ease, text-shadow 0.2s ease, border-color 0.2s ease, background 0.2s ease;
            text-align: center;
            padding: 1.2vh 3vh;
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            background: linear-gradient(
                to right,
                rgba(0, 30, 55, 0.4),
                rgba(0, 50, 80, 0.3)
            );
            margin-top: 1vh;
        }

        .guider-submit-btn:hover {
            color: #60d0ff;
            text-shadow: 0 0 14px rgba(60, 180, 255, 0.4);
            border-color: rgba(80, 180, 220, 0.5);
            background: linear-gradient(
                to right,
                rgba(0, 40, 70, 0.5),
                rgba(0, 60, 100, 0.4)
            );
        }

        /* askOption */
        .guider-options {
            display: flex;
            flex-wrap: wrap;
            gap: 1.5vh;
        }

        .guider-option {
            font-size: 2.5vh;
            padding: 1vh 2.5vh;
            border: 1px solid rgba(80, 180, 220, 0.2);
            border-radius: 0.5vh;
            cursor: pointer;
            color: rgba(160, 210, 240, 0.6);
            background: rgba(0, 15, 30, 0.4);
            transition: all 0.2s ease;
        }

        .guider-option:hover {
            color: #c8dce8;
            border-color: rgba(80, 180, 220, 0.4);
            background: rgba(0, 30, 55, 0.5);
        }

        .guider-option.selected {
            color: #60d0ff;
            border-color: rgba(80, 180, 220, 0.6);
            background: rgba(0, 40, 70, 0.5);
            text-shadow: 0 0 10px rgba(60, 180, 255, 0.3);
            box-shadow: 0 0 8px rgba(60, 180, 255, 0.15);
        }

        /* askOpen / shared textarea */
        .guider-textarea {
            width: 100%;
            min-height: 10vh;
            font-size: 3vh;
            font-family: 'Cabin Sketch', sans-serif;
            font-weight: bold;
            color: #c8dce8;
            background: rgba(0, 10, 20, 0.6);
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            padding: 2vh;
            box-sizing: border-box;
            resize: none;
            overflow: hidden;
            outline: none;
            transition: border-color 0.2s ease, box-shadow 0.2s ease;
            box-shadow: inset 0 0 10px rgba(0, 40, 80, 0.3);
        }

        .guider-textarea::placeholder {
            color: rgba(120, 180, 220, 0.35);
        }

        .guider-textarea:focus {
            border-color: rgba(80, 180, 220, 0.5);
            box-shadow: inset 0 0 14px rgba(0, 60, 120, 0.4);
        }

        /* askNumber / shared input */
        .guider-input {
            width: 100%;
            font-size: 3vh;
            font-family: 'Cabin Sketch', sans-serif;
            font-weight: bold;
            color: #c8dce8;
            background: rgba(0, 10, 20, 0.6);
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            padding: 1.5vh 2vh;
            box-sizing: border-box;
            outline: none;
            transition: border-color 0.2s ease, box-shadow 0.2s ease;
            box-shadow: inset 0 0 10px rgba(0, 40, 80, 0.3);
        }

        .guider-input::placeholder {
            color: rgba(120, 180, 220, 0.35);
        }

        .guider-input:focus {
            border-color: rgba(80, 180, 220, 0.5);
            box-shadow: inset 0 0 14px rgba(0, 60, 120, 0.4);
        }

        .guider-input::-webkit-inner-spin-button,
        .guider-input::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* askBoolean */
        .guider-boolean {
            display: flex;
            gap: 2vh;
        }

        .guider-bool-btn {
            flex: 1;
            font-size: 3vh;
            text-align: center;
            padding: 1.5vh 2vh;
            border: 1px solid rgba(80, 180, 220, 0.2);
            border-radius: 0.5vh;
            cursor: pointer;
            color: rgba(160, 210, 240, 0.6);
            background: rgba(0, 15, 30, 0.4);
            transition: all 0.2s ease;
        }

        .guider-bool-btn:hover {
            color: #c8dce8;
            border-color: rgba(80, 180, 220, 0.4);
            background: rgba(0, 30, 55, 0.5);
        }

        .guider-bool-btn.selected {
            color: #60d0ff;
            border-color: rgba(80, 180, 220, 0.6);
            background: rgba(0, 40, 70, 0.5);
            text-shadow: 0 0 10px rgba(60, 180, 255, 0.3);
            box-shadow: 0 0 8px rgba(60, 180, 255, 0.15);
        }

        /* askList */
        .guider-list {
            display: flex;
            flex-direction: column;
            gap: 1.5vh;
        }

        .guider-list-add-row {
            display: flex;
            gap: 1.5vh;
            align-items: center;
        }

        .guider-list-add-row .guider-input {
            flex: 1;
            min-width: 0;
        }

        .guider-list-add-btn {
            font-size: 3vh;
            padding: 1.2vh 2vh;
            border: 1px solid rgba(80, 180, 220, 0.25);
            border-radius: 0.5vh;
            cursor: pointer;
            color: rgba(120, 200, 240, 0.7);
            background: rgba(0, 15, 30, 0.4);
            transition: all 0.2s ease;
            flex-shrink: 0;
        }

        .guider-list-add-btn:hover {
            color: #60d0ff;
            border-color: rgba(80, 180, 220, 0.5);
            background: rgba(0, 30, 55, 0.5);
        }

        .guider-list-items {
            display: flex;
            flex-direction: column;
            gap: 0.8vh;
        }

        .guider-list-item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 1vh 1.5vh;
            border: 1px solid rgba(80, 180, 220, 0.15);
            border-radius: 0.5vh;
            background: rgba(0, 12, 24, 0.5);
            color: #c8dce8;
            font-size: 2.5vh;
        }

        .guider-list-item span {
            flex: 1;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .guider-list-remove {
            cursor: pointer;
            color: rgba(255, 120, 120, 0.6);
            font-size: 2.5vh;
            padding: 0 1vh;
            margin-left: 1vh;
            transition: color 0.2s ease;
            flex-shrink: 0;
        }

        .guider-list-remove:hover {
            color: #ff6b6b;
        }

        /* Loading overlay */
        .wizard-loading-overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 30;
            display: flex;
            flex-direction: column;
            gap: 2vh;
            align-items: center;
            justify-content: center;
            background: transparent;
            backdrop-filter: none;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.2s ease, backdrop-filter 0.3s ease;
        }

        .wizard-loading-overlay.visible {
            opacity: 1;
            pointer-events: auto;
            background: rgba(0, 5, 12, 0.45);
            backdrop-filter: blur(3px);
        }

        .wizard-spinner {
            width: 8vh;
            height: 8vh;
            border: 4px solid rgba(80, 180, 220, 0.15);
            border-top: 4px solid rgba(100, 200, 255, 0.7);
            border-radius: 50%;
            opacity: 0;
            transition: opacity 0.2s ease;
        }

        .wizard-loading-text {
            font-size: 3vh;
            color: rgba(160, 210, 240, 0.7);
            opacity: 0;
            transition: opacity 0.2s ease;
        }

        .wizard-loading-overlay.visible .wizard-loading-text {
            opacity: 1;
        }

        .wizard-loading-overlay.visible .wizard-spinner {
            opacity: 1;
            animation: wizard-spin 0.9s linear infinite;
        }

        @keyframes wizard-spin {
            to { transform: rotate(360deg); }
        }
      </style>
      <div class="wizard-overlay">
        <div class="wizard-title">
            <span>CardType Wizard</span>
            <span class="wizard-autosave">Saving...</span>
        </div>
        <div class="wizard-content">
            <slot></slot>
        </div>
        <div class="wizard-buttons">
            <div id="cancel-btn">Go Back</div>
        </div>
      </div>
    `;
    }
}

customElements.define('app-cardtype-wizard', CardTypeWizard);
