import { getJsScriptFromGenerator, isScriptTypeGeneratorFile, parseScriptGeneratorFrom } from '../../../script-generation/base.js';
import { playCancelSound, playConfirmSound, playHoverSound, setTempSoundDisable, stopAllAmbiencesAndStartNewOne } from '../../sound.js';
import './character-overview.js';

export class CardTypeWizard extends HTMLElement {
    constructor() {
        super();
        this.root = this.attachShadow({ mode: 'open' });
        this.onDocumentKeydown = this.onDocumentKeydown.bind(this);
        /** @type {number | null} */
        this._overlayTimer = null;
        /** @type {number | null} */
        this._autosaveHideTimer = null;
        /** @type {(() => void) | null} */
        this._wizardCleanup = null;
    }

    async connectedCallback() {
        this.render();

        document.addEventListener('keydown', this.onDocumentKeydown);

        this.root.getElementById('cancel-btn')?.addEventListener('click', () => {
            playCancelSound();
            setTempSoundDisable();
            this.remove();
        });

        this.root.querySelectorAll('.wizard-buttons div').forEach(btn => {
            btn.addEventListener('mouseenter', playHoverSound);
        });

        const overviewBtn = this.root.querySelector('.wizard-overview-button');
        if (overviewBtn) {
            overviewBtn.addEventListener('mouseenter', playHoverSound);
            overviewBtn.addEventListener('click', () => {
                this.openOverview();
            });
        }

        const prevBtn = this.root.querySelector('.wizard-prev-button');
        if (prevBtn) {
            prevBtn.addEventListener('mouseenter', playHoverSound);
            prevBtn.addEventListener('click', () => {
                playConfirmSound();
                this.onPrevButtonClick();
            });
        }

        this.initializeCard();

        await stopAllAmbiencesAndStartNewOne([{ src: './sounds/rem.mp3', volume: 1 }], 1000, 1000);
    }

    async initializeCard() {
        const characterId = this.getAttribute('character-id');
        const characterNamespace = this.getAttribute('character-namespace');
        if (!characterId || !characterNamespace) {
            console.error('CardTypeWizard requires character-id and character-namespace attributes');
            return;
        }

        /** @type {{src: string}} */
        let scriptSource;
        try {
            scriptSource = await window.ENGINE_WORKER_CLIENT.getRawScriptSource({ namespace: characterNamespace, id: characterId });
        } catch (err) {
            this.showError(err instanceof Error ? err.message : String(err));
            return;
        }

        /**
         * @type {boolean}
         */
        let isScriptTypeGenerator;
        try {
            isScriptTypeGenerator = isScriptTypeGeneratorFile(scriptSource.src);
        } catch (err) {
            this.showError('Failed to parse character script. It may be malformed or contain syntax errors.');
            return;
        }

        if (!isScriptTypeGenerator) {
            const contentArea = this.root.querySelector('.wizard-content');
            // @ts-ignore
            contentArea.innerHTML = `<p>This character script was not generated by the character wizard, so it can only be edited manually.</p>`;
        } else {
            let parsedCard;
            try {
                parsedCard = parseScriptGeneratorFrom(scriptSource.src);
            } catch (err) {
                this.showError('Failed to parse character script. It may be malformed or contain syntax errors.');
                return;
            }

            const isCompleteCard = parsedCard.state.guidedWizardCompleted || parsedCard.state.automaticWizardCompleted;
            if (isCompleteCard) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script has already been completed using the wizard</p>`;
                return;
            }

            if (parsedCard.state.version && parsedCard.state.version !== 2) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script was generated with version ${parsedCard.state.version} of the wizard, but you are currently running version 2. There may be incompatibilities that prevent the wizard from working correctly. Please update your character script by copying its content, creating a new character with the latest version of the wizard, and pasting the content into the new character's script.</p>`;
                return;
            }

            if (!parsedCard.state.language || parsedCard.state.language.split("-")[0] !== window.DREAMENGINE_LANGUAGE.split("-")[0]) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script is in a different language (${parsedCard.state.language || 'unknown'}) than the engine (${window.DREAMENGINE_LANGUAGE}). The wizard may not function correctly.</p>`;
                return;
            }

            let isAutomaticInProgress = parsedCard.state.automaticWizardInProgress && !parsedCard.state.automaticWizardCompleted;
            let isGuidedInProgress = parsedCard.state.guidedWizardInProgress && !parsedCard.state.guidedWizardCompleted;

            const isNewFile = scriptSource.src.startsWith("//@placeholder");

            if (isNewFile) {
                // new file check the options
                const wizardExpectation = this.getAttribute('wizard-expectation');
                if (wizardExpectation === 'automatic') {
                    isAutomaticInProgress = true;
                } else if (wizardExpectation === 'guided') {
                    isGuidedInProgress = true;
                }
            }

            if (isAutomaticInProgress || isGuidedInProgress) {
                const titleName = isAutomaticInProgress ? 'Automatic Wizard' : 'Guided Wizard';
                const titleText = this.root.querySelector('.wizard-title span:first-child');
                if (titleText) {
                    titleText.textContent = titleName;
                }

                if (isAutomaticInProgress) {
                    this.startMode(parsedCard, 'automatic', isNewFile);
                } else {
                    this.startMode(parsedCard, 'guided', isNewFile);
                }
            } else {
                const contentArea = this.root.querySelector('.wizard-content');
                // unknown state, should not happen, say that it's probably another version of the wizard and not this one
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script is in an unknown state. It may have been generated by an older/newer version of the wizard, or there may be an issue with the script. Please edit the script manually or try regenerating it with the latest version of the wizard.</p>`;
            }
        }
    }

    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {"automatic" | "guided"} mode 
     * @param {boolean} isNewFile
     */
    startMode(parsedCard, mode, isNewFile) {
        if (isNewFile) {
            const contentArea = this.root.querySelector('.wizard-content');
            if (!contentArea) return;

            const buttonLabel = mode === 'automatic' ? 'Automatic Start' : 'Guided Start';

            contentArea.innerHTML = `
                <div class="wizard-card-input">
                    <textarea class="card-textarea" placeholder="Paste your character card here..."></textarea>
                    <div class="wizard-start-btn">${buttonLabel}</div>
                </div>
            `;

            const textarea = contentArea.querySelector('.card-textarea');
            if (textarea) {
                textarea.addEventListener('input', function () {
                    // @ts-ignore
                    this.style.height = 'auto';
                    // @ts-ignore
                    this.style.height = this.scrollHeight + 'px';
                });
            }

            const startBtn = contentArea.querySelector('.wizard-start-btn');
            if (startBtn) {
                startBtn.addEventListener('mouseenter', playHoverSound);
                startBtn.addEventListener('click', () => {
                    playConfirmSound();
                    // @ts-ignore
                    const cardText = (textarea?.value || '').trim();
                    if (!cardText) {
                        return;
                    }
                    parsedCard.state.card = cardText;
                    if (mode === 'automatic') {
                        parsedCard.state.automaticWizardInProgress = true;
                        parsedCard.state.automaticWizardCompleted = false;
                    } else {
                        parsedCard.state.guidedWizardInProgress = true;
                        parsedCard.state.guidedWizardCompleted = false;
                    }
                    this.continueProcess(parsedCard, mode);
                });
            }
        } else {
            this.continueProcess(parsedCard, mode);
        }
    }


    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {"automatic" | "guided"} mode
     */
    async continueProcess(parsedCard, mode) {
        const guided = mode === 'guided';
        const guider = this.createGuider(guided);
        const client = window.ENGINE_WORKER_CLIENT;

        const characterId = this.getAttribute('character-id');
        const characterNamespace = this.getAttribute('character-namespace');

        if (!characterId || !characterNamespace) {
            console.error('Character ID or namespace is missing.');
            return;
        }

        document.querySelector(".wizard-prev-button")?.classList.add("visible");

        // Wire up guider questions from worker → UI → answer back
        /** @param {any} data */
        const onGuiderQuestion = async (data) => {
            const { id, qid, questionType, question, options, defaultValue, currentCard } = data;

            await this.save(currentCard);

            /** @type {{value: any}} */
            let result;
            switch (questionType) {
                case 'askOption':
                    result = await guider.askOption(id, question, options, defaultValue);
                    break;
                case 'askOpen':
                    result = await guider.askOpen(id, question, defaultValue);
                    break;
                case 'askAccept':
                    result = await guider.askAccept(id, question, defaultValue);
                    break;
                case 'askNumber':
                    result = await guider.askNumber(id, question, defaultValue);
                    break;
                case 'askBoolean':
                    result = await guider.askBoolean(id, question, defaultValue);
                    break;
                case 'askList':
                    result = await guider.askList(id, question, options, defaultValue);
                    break;
                case 'askArbitraryList':
                    result = await guider.askArbitraryList(id, question, defaultValue);
                    break;
                case 'askAcceptArbitraryList':
                    result = await guider.askAcceptArbitraryList(id, question, defaultValue);
                    break;
                default:
                    result = { value: defaultValue };
            }

            client.sendGuiderAnswer({ qid, value: result.value });
        };

        /** @param {any} data */
        const onComplete = (data) => {
            data.currentCard.state.automaticWizardInProgress = false;
            data.currentCard.state.guidedWizardInProgress = false;
            data.currentCard.state.automaticWizardCompleted = true;
            data.currentCard.state.guidedWizardCompleted = true;
            this.save(data.currentCard, true);
            this.endOverlay();
            cleanup();
        };

        const cleanup = () => {
            client.onScriptTypeGuiderQuestion = null;
            client.onCardTypeWizardComplete = null;
        };

        // Store cleanup so disconnectedCallback can call it
        this._wizardCleanup = () => {
            cleanup();
            client.cancelCardTypeGeneration();
        };

        client.onScriptTypeGuiderQuestion = onGuiderQuestion;
        client.onCardTypeWizardComplete = onComplete;

        this.initOverlay();

        try {
            /**
             * @type {import('../../../script-generation/base.js').ScriptTypeGenerator}
             */
            const copiedParsedCardWithoutCode = {
                body: [],
                foot: [],
                imports: [],
                head: [],
                state: parsedCard.state || {},
            };
            await client.continueCardTypeWizard({ currentCard: copiedParsedCardWithoutCode, guided, language: window.DREAMENGINE_LANGUAGE });
        } catch (err) {
            cleanup();
            this.showError(err instanceof Error ? err.message : String(err));
            return;
        }

        // If the element was removed (user clicked Go Back / cancelled), stop here
        if (!this.isConnected) return;

        console.log('CardTypeWizard process complete for character:', characterId);

        this.showDone();
    }

    onPrevButtonClick() {
        const client = window.ENGINE_WORKER_CLIENT;
        if (client) {
            client.goBackInCardTypeWizard();
        }
    }

    openOverview() {
        const overview = document.createElement('app-character-overview');
        document.body.appendChild(overview);
    }

    showDone() {
        this.endOverlay();
        const contentArea = this.root.querySelector('.wizard-content');
        if (contentArea) {
            contentArea.innerHTML = '<div class="guider-label" style="text-align:center;margin-top:6vh;">Done!</div>';
        }
    }

    /**
     * Shows an error message in the wizard content area and stops the spinner.
     * @param {string} message
     */
    showError(message) {
        this.endOverlay();
        const contentArea = this.root.querySelector('.wizard-content');
        if (contentArea) {
            contentArea.innerHTML = `<div class="guider-label" style="text-align:center;margin-top:6vh;color:#ff6b6b;font-size:6vh">Error</div>
                <div class="guider-label" style="text-align:center;margin-top:1vh;font-size:3vh;white-space:pre-wrap;word-break:break-word;">${this.escapeHtml(message)}</div>`;
        }
    }

    /**
     * @param {string} str
     * @returns {string}
     */
    escapeHtml(str) {
        const div = document.createElement('div');
        div.textContent = str;
        return div.innerHTML;
    }

    /**
     * Creates a UI-based guider that renders interactive questions into the wizard content area.
     * Each method returns a promise that resolves when the user submits their answer.
     * @param {boolean} isGuided
     * @returns {import('../../../script-generation/base.js').ScriptTypeGuider}
     */
    createGuider(isGuided) {
        const self = this;

        const _highlightPhrases = [
            'strongly physically attractive',
            'moderately physically attractive',
            'slightly physically attractive',
            'non physically attractive',
            'bestial or feral',
            'strongly attractive',
            'moderately attractive',
            'slightly attractive',
            'hostile presences',
            'hostile presence',
            'sworn enemies',
            'sworn enemy',
            'close friends',
            'close friend',
            'best friends',
            'best friend',
            'good friends',
            'good friend',
            'in private',
            'in public',
            'bad impression',
            'good impression',
            'wild creatures',
            'wild creature',
            'animal',
            'physical affection',
            'intimate affection',
            'around friends',
            'around family',
            'acquaintance',
            'acquainted with',
            'antagonist',
            'animals',
            'animal',
            'affectionate',
            'affection',
            'non-romantic',
            'romantic',
            'unfriendly',
            'unpleasant',
            'strangers',
            'stranger',
            'ambiguous',
            'intersex',
            'hostile',
            'friendly',
            'friend',
            'family',
            'females',
            'female',
            'males',
            'male',
            'any gender/sex',
            'sexually',
            'bisexual',
            'pansexual',
            'asexual',
            'sexual',
            'sex',
            'pet',
        ];
        const _highlightPattern = new RegExp(
            '(' + _highlightPhrases.map(p => p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')',
            'gi'
        );

        /** @param {string} text */
        function highlightKeywordsInQuestion(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML.replace(_highlightPattern, '<strong style="color:#e07070">$1</strong>');
        }

        /**
         * Renders a question into the content area and returns a promise.
         * @param {string} question
         * @param {() => HTMLElement} buildInputFn - builds the input element(s)
         * @param {(container: HTMLElement) => any} extractValueFn - extracts the value on submit
         * @param {any} defaultValue
         * @param {boolean} [hasTryAgainOption]
         * @returns {Promise<any>}
         */
        function presentQuestion(question, buildInputFn, extractValueFn, defaultValue, hasTryAgainOption) {
            return new Promise((resolve) => {
                self.endOverlay();

                const contentArea = self.root.querySelector('.wizard-content');
                if (!contentArea) { resolve(defaultValue); return; }

                contentArea.innerHTML = '';

                const container = document.createElement('div');
                container.className = 'guider-question';

                const questionLabel = document.createElement('div');
                questionLabel.className = 'guider-label';
                questionLabel.innerHTML = highlightKeywordsInQuestion(question);
                container.appendChild(questionLabel);

                const inputArea = buildInputFn();
                container.appendChild(inputArea);

                const buttonsContainer = document.createElement('div');
                buttonsContainer.className = 'buttons-container';
                container.appendChild(buttonsContainer);

                if (hasTryAgainOption) {
                    const tryAgainBtn = document.createElement('div');
                    tryAgainBtn.className = 'guider-try-again-btn';
                    tryAgainBtn.textContent = 'Try Again';
                    tryAgainBtn.addEventListener('mouseenter', playHoverSound);
                    tryAgainBtn.addEventListener('click', () => {
                        playCancelSound();
                        setTempSoundDisable();
                        self.initOverlay();
                        resolve(null);
                    });
                    buttonsContainer.appendChild(tryAgainBtn);
                }

                const submitBtn = document.createElement('div');
                submitBtn.className = 'guider-submit-btn';
                submitBtn.textContent = 'Confirm';
                submitBtn.addEventListener('mouseenter', playHoverSound);
                submitBtn.addEventListener('click', () => {
                    playConfirmSound();
                    const value = extractValueFn(inputArea);
                    self.initOverlay();
                    resolve(value);
                });
                buttonsContainer.appendChild(submitBtn);

                contentArea.appendChild(container);
            });
        }

        /**
         * @param {string} question
         * @param {string[]} [defaultValue]
         * @param {boolean} [hasTryAgainOption]
         * @returns {Promise<string[]>}
         */
        function presentArbitraryList(question, defaultValue, hasTryAgainOption) {
            return presentQuestion(
                question,
                () => {
                    const wrapper = document.createElement('div');
                    wrapper.className = 'guider-list';

                    /** @type {string[]} */
                    const items = defaultValue ? [...defaultValue] : [];

                    const syncItemsFromDom = () => {
                        const listContainer = wrapper.querySelector('.guider-list-items');
                        if (!listContainer) return;
                        const spans = listContainer.querySelectorAll('.guider-list-item span');
                        spans.forEach((span, idx) => {
                            if (idx < items.length) items[idx] = span.textContent || '';
                        });
                    };

                    const renderItems = () => {
                        let listContainer = wrapper.querySelector('.guider-list-items');
                        if (!listContainer) {
                            listContainer = document.createElement('div');
                            listContainer.className = 'guider-list-items';
                            wrapper.insertBefore(listContainer, wrapper.querySelector('.guider-list-add-row'));
                        }
                        listContainer.innerHTML = '';
                        items.forEach((item, idx) => {
                            const itemEl = document.createElement('div');
                            itemEl.className = 'guider-list-item';

                            const span = document.createElement('span');
                            span.setAttribute('contenteditable', 'plaintext-only');
                            span.setAttribute('spellcheck', 'true');
                            span.textContent = item;
                            // Fallback for browsers that don't support plaintext-only:
                            // strip rich content from pasted data and block enter newlines.
                            span.addEventListener('paste', (e) => {
                                e.preventDefault();
                                const text = e.clipboardData?.getData('text/plain') ?? '';
                                const selection = window.getSelection();
                                if (!selection || selection.rangeCount === 0) return;
                                const range = selection.getRangeAt(0);
                                range.deleteContents();
                                range.insertNode(document.createTextNode(text));
                                range.collapse(false);
                            });
                            span.addEventListener('keydown', (e) => {
                                if (e.key === 'Enter') e.preventDefault();
                            });
                            itemEl.appendChild(span);

                            const removeBtn = document.createElement('div');
                            removeBtn.className = 'guider-list-remove';
                            removeBtn.dataset.idx = String(idx);
                            removeBtn.textContent = '✕';
                            removeBtn.addEventListener('mouseenter', playHoverSound);
                            removeBtn.addEventListener('click', () => {
                                syncItemsFromDom();
                                items.splice(idx, 1);
                                renderItems();
                            });
                            itemEl.appendChild(removeBtn);

                            listContainer.appendChild(itemEl);
                        });
                    };

                    const addRow = document.createElement('div');
                    addRow.className = 'guider-list-add-row';

                    const textarea = document.createElement('textarea');
                    textarea.className = 'guider-textarea';
                    textarea.placeholder = 'Add item...';
                    textarea.addEventListener('input', function () {
                        this.style.height = 'auto';
                        this.style.height = this.scrollHeight + 'px';
                    });

                    const addBtn = document.createElement('div');
                    addBtn.className = 'guider-list-add-btn';
                    addBtn.textContent = '+';
                    addBtn.addEventListener('mouseenter', playHoverSound);
                    addBtn.addEventListener('click', () => {
                        const val = textarea.value.trim();
                        if (!val) return;
                        syncItemsFromDom();
                        items.push(val);
                        textarea.value = '';
                        textarea.style.height = 'auto';
                        renderItems();
                    });

                    addRow.appendChild(textarea);
                    addRow.appendChild(addBtn);
                    wrapper.appendChild(addRow);

                    renderItems();
                    return wrapper;
                },
                (inputArea) => {
                    const itemEls = inputArea.querySelectorAll('.guider-list-item span');
                    const result = Array.from(itemEls).map(el => el.textContent || '');
                    const pending = inputArea.querySelector('.guider-list-add-row .guider-textarea');
                    if (pending) {
                        const val = /** @type {HTMLTextAreaElement} */ (pending).value.trim();
                        if (val && !result.includes(val)) result.push(val);
                    }
                    return result.length > 0 ? result : (defaultValue ?? []);
                },
                defaultValue,
                hasTryAgainOption
            );
        }

        return {
            async askOption(id, question, options, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-options';
                        options.forEach((opt, i) => {
                            const optValue = typeof opt === 'string' ? opt : opt.value;
                            const optLabel = typeof opt === 'string' ? opt : opt.label;
                            const optBtn = document.createElement('div');
                            optBtn.className = 'guider-option';
                            if (optValue === defaultValue) optBtn.classList.add('selected');
                            optBtn.dataset.value = optValue;
                            optBtn.textContent = optLabel;
                            optBtn.addEventListener('mouseenter', playHoverSound);
                            optBtn.addEventListener('click', () => {
                                wrapper.querySelectorAll('.guider-option').forEach(b => b.classList.remove('selected'));
                                optBtn.classList.add('selected');
                            });
                            wrapper.appendChild(optBtn);
                        });
                        return wrapper;
                    },
                    (inputArea) => {
                        const selected = inputArea.querySelector('.guider-option.selected');
                        const firstValue = options[0] !== undefined ? (typeof options[0] === 'string' ? options[0] : options[0].value) : undefined;
                        return selected ? /** @type {HTMLElement} */ (selected).dataset.value : (defaultValue ?? firstValue);
                    },
                    defaultValue
                );

                return { value: finalValue };
            },

            async askOpen(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const textarea = document.createElement('textarea');
                        textarea.className = 'guider-textarea';
                        textarea.placeholder = defaultValue || '';
                        if (defaultValue) textarea.value = defaultValue;
                        textarea.addEventListener('input', function () {
                            this.style.height = 'auto';
                            this.style.height = this.scrollHeight + 'px';
                        });
                        requestAnimationFrame(() => {
                            textarea.style.height = 'auto';
                            textarea.style.height = textarea.scrollHeight + 'px';
                        });
                        setTimeout(() => {
                            requestAnimationFrame(() => {
                                textarea.style.height = 'auto';
                                textarea.style.height = textarea.scrollHeight + 'px';
                            });
                        }, 100);
                        return textarea;
                    },
                    (inputArea) => {
                        return /** @type {HTMLTextAreaElement} */ (inputArea).value || defaultValue || '';
                    },
                    defaultValue
                );

                return { value: finalValue };
            },

            async askAccept(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const textarea = document.createElement('textarea');
                        textarea.className = 'guider-textarea';
                        textarea.placeholder = defaultValue || '';
                        if (defaultValue) textarea.value = defaultValue;
                        textarea.addEventListener('input', function () {
                            this.style.height = 'auto';
                            this.style.height = this.scrollHeight + 'px';
                        });
                        requestAnimationFrame(() => {
                            textarea.style.height = 'auto';
                            textarea.style.height = textarea.scrollHeight + 'px';
                        });
                        setTimeout(() => {
                            requestAnimationFrame(() => {
                                textarea.style.height = 'auto';
                                textarea.style.height = textarea.scrollHeight + 'px';
                            });
                        }, 100);
                        return textarea;
                    },
                    (inputArea) => {
                        return /** @type {HTMLTextAreaElement} */ (inputArea).value || defaultValue || '';
                    },
                    defaultValue,
                    true // hasTryAgainOption
                );

                return { value: finalValue };
            },

            async askNumber(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const input = document.createElement('input');
                        input.className = 'guider-input';
                        input.type = 'number';
                        if (defaultValue !== undefined) input.value = String(defaultValue);
                        input.placeholder = defaultValue !== undefined ? String(defaultValue) : '0';
                        return input;
                    },
                    (inputArea) => {
                        const num = parseFloat(/** @type {HTMLInputElement} */(inputArea).value);
                        return isNaN(num) ? (defaultValue ?? 0) : num;
                    },
                    defaultValue
                );

                return { value: finalValue };
            },

            async askBoolean(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-boolean';

                        const yesBtn = document.createElement('div');
                        yesBtn.className = 'guider-bool-btn';
                        yesBtn.textContent = 'Yes';
                        if (defaultValue === true) yesBtn.classList.add('selected');

                        const noBtn = document.createElement('div');
                        noBtn.className = 'guider-bool-btn';
                        noBtn.textContent = 'No';
                        if (defaultValue === false) noBtn.classList.add('selected');

                        yesBtn.addEventListener('mouseenter', playHoverSound);
                        noBtn.addEventListener('mouseenter', playHoverSound);

                        yesBtn.addEventListener('click', () => {
                            yesBtn.classList.add('selected');
                            noBtn.classList.remove('selected');
                        });
                        noBtn.addEventListener('click', () => {
                            noBtn.classList.add('selected');
                            yesBtn.classList.remove('selected');
                        });

                        wrapper.appendChild(yesBtn);
                        wrapper.appendChild(noBtn);
                        return wrapper;
                    },
                    (inputArea) => {
                        const yesBtn = inputArea.querySelector('.guider-bool-btn:first-child');
                        return yesBtn?.classList.contains('selected') ?? (defaultValue ?? false);
                    },
                    defaultValue
                );

                return { value: finalValue };
            },

            // @ts-ignore
            async askArbitraryList(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentArbitraryList(question, defaultValue, false);

                return { value: finalValue };
            },

            async askAcceptArbitraryList(id, question, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;
                const finalValue = await presentArbitraryList(question, defaultValue || undefined, true);

                return { value: finalValue };
            },

            async askList(id, question, options, defaultValueFnOrValue) {
                const defaultValue = typeof defaultValueFnOrValue === 'function' ? await defaultValueFnOrValue() : defaultValueFnOrValue;

                const finalValue = await presentQuestion(
                    question,
                    () => {
                        const wrapper = document.createElement('div');
                        wrapper.className = 'guider-list';

                        /** @type {string[]} */
                        const items = defaultValue ? [...defaultValue] : [];

                        const valueToLabel = new Map();
                        if (options) {
                            for (const group of Object.values(options)) {
                                for (const o of group) {
                                    if (typeof o === 'string') valueToLabel.set(o, o);
                                    else valueToLabel.set(o.value, o.label);
                                }
                            }
                        }

                        const renderItems = () => {
                            let listContainer = wrapper.querySelector('.guider-list-items');
                            if (!listContainer) {
                                listContainer = document.createElement('div');
                                listContainer.className = 'guider-list-items';
                                wrapper.insertBefore(listContainer, wrapper.querySelector('.guider-list-add-row'));
                            }
                            listContainer.innerHTML = items.map((item, idx) => `
                                <div class="guider-list-item">
                                    <span data-value="${item}">${valueToLabel.get(item) ?? item}</span>
                                    <div class="guider-list-remove" data-idx="${idx}">✕</div>
                                </div>
                            `).join('');
                            listContainer.querySelectorAll('.guider-list-remove').forEach(btn => {
                                btn.addEventListener('mouseenter', playHoverSound);
                                btn.addEventListener('click', () => {
                                    const idx = parseInt(/** @type {HTMLElement} */(btn).dataset.idx || '0');
                                    items.splice(idx, 1);
                                    renderItems();
                                    if (options) rebuildAddInput();
                                });
                            });
                        };

                        const addRow = document.createElement('div');
                        addRow.className = 'guider-list-add-row';

                        /** @type {HTMLInputElement | HTMLSelectElement} */
                        let addInput;

                        const rebuildAddInput = () => {
                            const oldInput = addRow.querySelector('.guider-input');
                            if (oldInput) oldInput.remove();

                            if (options) {
                                const select = document.createElement('select');
                                select.className = 'guider-input';
                                let hasAny = false;
                                const groups = Object.keys(options);
                                for (const group of groups) {
                                    const remaining = options[group].filter(o => {
                                        const optVal = typeof o === 'string' ? o : o.value;
                                        return !items.includes(optVal);
                                    });
                                    if (remaining.length === 0) continue;
                                    hasAny = true;
                                    const optgroup = document.createElement('optgroup');
                                    optgroup.label = group;
                                    remaining.forEach(opt => {
                                        const o = document.createElement('option');
                                        o.value = typeof opt === 'string' ? opt : opt.value;
                                        o.textContent = typeof opt === 'string' ? opt : opt.label;
                                        optgroup.appendChild(o);
                                    });
                                    select.appendChild(optgroup);
                                }
                                if (!hasAny) {
                                    const placeholder = document.createElement('option');
                                    placeholder.value = '';
                                    placeholder.textContent = 'No more options';
                                    placeholder.disabled = true;
                                    placeholder.selected = true;
                                    select.appendChild(placeholder);
                                    select.disabled = true;
                                } else {
                                    const placeholder = document.createElement('option');
                                    placeholder.value = '';
                                    placeholder.textContent = 'Select an option...';
                                    placeholder.disabled = true;
                                    placeholder.selected = true;
                                    select.insertBefore(placeholder, select.firstChild);
                                }
                                addInput = select;
                            } else {
                                const input = document.createElement('input');
                                input.className = 'guider-input';
                                input.type = 'text';
                                input.placeholder = 'Add item...';
                                addInput = input;
                            }
                            addRow.insertBefore(addInput, addRow.querySelector('.guider-list-add-btn'));
                        };

                        const addBtn = document.createElement('div');
                        addBtn.className = 'guider-list-add-btn';
                        addBtn.textContent = '+';
                        addBtn.addEventListener('mouseenter', playHoverSound);
                        addBtn.addEventListener('click', () => {
                            const val = addInput.value.trim();
                            if (!val) return;
                            items.push(val);
                            addInput.value = '';
                            renderItems();
                            if (options) rebuildAddInput();
                        });

                        addRow.appendChild(addBtn);
                        wrapper.appendChild(addRow);
                        rebuildAddInput();

                        renderItems();
                        return wrapper;
                    },
                    (inputArea) => {
                        const itemEls = inputArea.querySelectorAll('.guider-list-item span');
                        const result = Array.from(itemEls).map(el => /** @type {HTMLElement} */ (el).dataset.value || el.textContent || '');
                        const pending = inputArea.querySelector('.guider-list-add-row .guider-input');
                        if (pending) {
                            // @ts-ignore
                            const val = pending.value.trim();
                            if (val && !result.includes(val)) result.push(val);
                        }
                        return result.length > 0 ? result : (defaultValue ?? []);
                    },
                    defaultValue
                );

                return { value: finalValue };
            }
        };
    }

    /**
     * Starts a loading overlay. After 300ms the overlay becomes visible with blur and a spinner.
     * Call endOverlay() to remove it.
     */
    initOverlay() {
        this.endOverlay();

        const overlay = document.createElement('div');
        overlay.className = 'wizard-loading-overlay';
        overlay.innerHTML = '<div class="wizard-spinner"></div><div class="wizard-loading-text">Running inference...</div>';
        this.root.querySelector('.wizard-content')?.appendChild(overlay);

        this._overlayTimer = window.setTimeout(() => {
            overlay.classList.add('visible');
            this._overlayTimer = null;
        }, 300);
    }

    /**
     * Removes the loading overlay immediately, cancelling the 300ms timer if still pending.
     */
    endOverlay() {
        if (this._overlayTimer !== null) {
            clearTimeout(this._overlayTimer);
            this._overlayTimer = null;
        }
        this.root.querySelector('.wizard-loading-overlay')?.remove();
    }

    /**
     * Shows the autosave indicator in the title bar as "Saving...".
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {boolean} completed
     */
    async save(parsedCard, completed = false) {
        // TODO prevent racing of many saves when questions are being fired too fast, somehow at startup or on non-guided mode
        this.lastSavedCard = parsedCard;
        const jsContent = getJsScriptFromGenerator(parsedCard, undefined, undefined, completed ? [] : ["initialize"]);
        const characterId = this.getAttribute('character-id') || "";
        const characterNamespace = this.getAttribute('character-namespace') || "";
        this.showAutosaveStatus();
        await window.API.updateScriptFile(
            characterNamespace,
            characterId,
            jsContent
        );
        this.hideAutosaveStatus();
    };

    showAutosaveStatus() {
        if (this._autosaveHideTimer) {
            clearTimeout(this._autosaveHideTimer);
            this._autosaveHideTimer = null;
        }
        const el = this.root.querySelector('.wizard-autosave');
        if (el) {
            el.textContent = 'Saving...';
            el.classList.add('visible');
            el.classList.remove('saved');
        }
    }

    /**
     * Shows "Saved" and fades out the autosave indicator after a short delay.
     */
    hideAutosaveStatus() {
        const el = this.root.querySelector('.wizard-autosave');
        if (el) {
            el.textContent = 'Saved';
            el.classList.add('saved');
        }
        this._autosaveHideTimer = window.setTimeout(() => {
            if (el) {
                el.classList.remove('visible');
                el.classList.remove('saved');
            }
            this._autosaveHideTimer = null;
        }, 2000);
    }

    async disconnectedCallback() {
        this.endOverlay();
        if (this._autosaveHideTimer) {
            clearTimeout(this._autosaveHideTimer);
            this._autosaveHideTimer = null;
        }
        if (this._wizardCleanup) {
            this._wizardCleanup();
            this._wizardCleanup = null;
        }
        document.removeEventListener('keydown', this.onDocumentKeydown);
        this.dispatchEvent(new CustomEvent('wizard-closed'));

        await stopAllAmbiencesAndStartNewOne([{ src: './sounds/dream-ambience.mp3', volume: 3 }], 1000, 1000);
    }

    /** @param {KeyboardEvent} e */
    onDocumentKeydown(e) {
        if (e.key === 'Escape') {
            if (document.querySelector('app-dialog')) return;
            const bodyChildren = Array.from(document.body.children);
            if (bodyChildren[bodyChildren.length - 1] !== this) return;
            playCancelSound();
            setTempSoundDisable();
            this.remove();
        }
    }

    render() {
        this.root.innerHTML = `
      <style>
        @import "./components/wizard/wizard.css";
      </style>
      <div class="wizard-overlay">
        <div class="wizard-title">
            <span>CardType Wizard</span>
            <div class="wizard-title-right">
                <span class="wizard-autosave"></span>
                <div class="wizard-overview-button">overview</div>
                <div class="wizard-prev-button">prev</div>
            </div>
        </div>
        <div class="wizard-content">
            <slot></slot>
        </div>
        <div class="wizard-buttons">
            <div id="cancel-btn">Go Back</div>
        </div>
      </div>
    `;
    }
}

customElements.define('app-cardtype-wizard', CardTypeWizard);
