import { getJsScriptFromGenerator, isScriptTypeGeneratorFile, parseScriptGeneratorFrom } from '../../../script-generation/base.js';
import { playConfirmSound, playHoverSound, randomizeAmbienceGroupSrc, stopAllAmbiencesAndStartNewOne } from '../../sound.js';
import { GeneralWizard } from './wizard.js';
import './character-overview.js';

export class CardTypeWizard extends GeneralWizard {
    constructor() {
        super();
        /** @type {Promise<void> | null} */
        this._saveLoopPromise = null;
        /** @type {{ parsedCard: import('../../../script-generation/base.js').ScriptTypeGenerator, completed: boolean } | null} */
        this._pendingSave = null;
        /** @type {(() => void) | null} */
        this._wizardCleanup = null;
    }

    getTitle() {
        return 'CardType Wizard';
    }

    renderHeaderExtras() {
        return `<div class="wizard-overview-button">overview</div>`;
    }

    async onConnected() {
        const overviewBtn = this.root.querySelector('.wizard-overview-button');
        if (overviewBtn) {
            overviewBtn.addEventListener('mouseenter', playHoverSound);
            overviewBtn.addEventListener('click', () => {
                this.openOverview();
            });
        }

        this.initializeCard();

        await stopAllAmbiencesAndStartNewOne([{ id: 'dream-world', srcs: randomizeAmbienceGroupSrc(
            [
                { src: './sounds/dream-world.mp3', fadeDurationMs: 1000, volume: 3 },
                { src: './sounds/rem-with-fade.mp3', fadeDurationMs: 1000, volume: 1 },
                { src: './sounds/critter.mp3', fadeDurationMs: 1000, volume: 1.5 },
            ],
        ) }], 1000);
    }

    async onDisconnected() {
        if (this._wizardCleanup) {
            this._wizardCleanup();
            this._wizardCleanup = null;
        }

        await stopAllAmbiencesAndStartNewOne([{ id: 'dream-ambience', srcs: [{ src: window.DREAM_AMBIENCE_CHOSEN, fadeDurationMs: 2000, volume: window.DREAM_AMBIENCE_CHOSEN_VOLUME }] }], 1000);
    }

    async initializeCard() {
        const characterId = this.getAttribute('character-id');
        const characterNamespace = this.getAttribute('character-namespace');
        if (!characterId || !characterNamespace) {
            console.error('CardTypeWizard requires character-id and character-namespace attributes');
            return;
        }

        /** @type {{src: string}} */
        let scriptSource;
        try {
            scriptSource = await window.ENGINE_WORKER_CLIENT.getRawScriptSource({ namespace: characterNamespace, id: characterId });
        } catch (err) {
            this.showError(err instanceof Error ? err.message : String(err));
            return;
        }

        /**
         * @type {boolean}
         */
        let isScriptTypeGenerator;
        try {
            isScriptTypeGenerator = isScriptTypeGeneratorFile(scriptSource.src);
        } catch (err) {
            this.showError('Failed to parse character script. It may be malformed or contain syntax errors.');
            return;
        }

        if (!isScriptTypeGenerator) {
            const contentArea = this.root.querySelector('.wizard-content');
            // @ts-ignore
            contentArea.innerHTML = `<p>This character script was not generated by the character wizard, so it can only be edited manually.</p>`;
        } else {
            let parsedCard;
            try {
                parsedCard = parseScriptGeneratorFrom(scriptSource.src);
            } catch (err) {
                this.showError('Failed to parse character script. It may be malformed or contain syntax errors.');
                return;
            }

            const isCompleteCard = parsedCard.state.guidedWizardCompleted || parsedCard.state.automaticWizardCompleted;
            if (isCompleteCard) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script has already been completed using the wizard</p>`;
                return;
            }

            if (parsedCard.state.version && parsedCard.state.version !== 2) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script was generated with version ${parsedCard.state.version} of the wizard, but you are currently running version 2. There may be incompatibilities that prevent the wizard from working correctly. Please update your character script by copying its content, creating a new character with the latest version of the wizard, and pasting the content into the new character's script.</p>`;
                return;
            }

            if (!parsedCard.state.language || parsedCard.state.language.split("-")[0] !== window.DREAMENGINE_LANGUAGE.split("-")[0]) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script is in a different language (${parsedCard.state.language || 'unknown'}) than the engine (${window.DREAMENGINE_LANGUAGE}). The wizard may not function correctly.</p>`;
                return;
            }

            let isAutomaticInProgress = parsedCard.state.automaticWizardInProgress && !parsedCard.state.automaticWizardCompleted;
            let isGuidedInProgress = parsedCard.state.guidedWizardInProgress && !parsedCard.state.guidedWizardCompleted;

            const isNewFile = scriptSource.src.startsWith("//@placeholder");

            if (isNewFile) {
                // new file check the options
                const wizardExpectation = this.getAttribute('wizard-expectation');
                if (wizardExpectation === 'automatic') {
                    isAutomaticInProgress = true;
                } else if (wizardExpectation === 'guided') {
                    isGuidedInProgress = true;
                }
            }

            if (isAutomaticInProgress || isGuidedInProgress) {
                const titleName = isAutomaticInProgress ? 'Automatic Wizard' : 'Guided Wizard';
                const titleText = this.root.querySelector('.wizard-title span:first-child');
                if (titleText) {
                    titleText.textContent = titleName;
                }

                if (isAutomaticInProgress) {
                    this.startMode(parsedCard, 'automatic', isNewFile);
                } else {
                    this.startMode(parsedCard, 'guided', isNewFile);
                }
            } else {
                const contentArea = this.root.querySelector('.wizard-content');
                // unknown state, should not happen, say that it's probably another version of the wizard and not this one
                // @ts-ignore
                contentArea.innerHTML = `<p>This character script is in an unknown state. It may have been generated by an older/newer version of the wizard, or there may be an issue with the script. Please edit the script manually or try regenerating it with the latest version of the wizard.</p>`;
            }
        }
    }

    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {"automatic" | "guided"} mode 
     * @param {boolean} isNewFile
     */
    startMode(parsedCard, mode, isNewFile) {
        if (isNewFile) {
            const contentArea = this.root.querySelector('.wizard-content');
            if (!contentArea) return;

            const buttonLabel = mode === 'automatic' ? 'Automatic Start' : 'Guided Start';

            contentArea.innerHTML = `
                <div class="wizard-card-input">
                    <textarea class="card-textarea" placeholder="Paste your character card here..."></textarea>
                    <div class="wizard-start-btn">${buttonLabel}</div>
                </div>
            `;

            const textarea = contentArea.querySelector('.card-textarea');
            if (textarea) {
                textarea.addEventListener('input', function () {
                    // @ts-ignore
                    this.style.height = 'auto';
                    // @ts-ignore
                    this.style.height = this.scrollHeight + 'px';
                });
            }

            const startBtn = contentArea.querySelector('.wizard-start-btn');
            if (startBtn) {
                startBtn.addEventListener('mouseenter', playHoverSound);

                let submitted = false;

                startBtn.addEventListener('click', () => {
                    if (submitted) return;
                    submitted = true;
                    playConfirmSound();
                    // @ts-ignore
                    const cardText = (textarea?.value || '').trim();
                    if (!cardText) {
                        return;
                    }
                    parsedCard.state.card = cardText;
                    if (mode === 'automatic') {
                        parsedCard.state.automaticWizardInProgress = true;
                        parsedCard.state.automaticWizardCompleted = false;
                    } else {
                        parsedCard.state.guidedWizardInProgress = true;
                        parsedCard.state.guidedWizardCompleted = false;
                    }
                    this.continueProcess(parsedCard, mode);
                });
            }
        } else {
            this.continueProcess(parsedCard, mode);
        }
    }


    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {"automatic" | "guided"} mode
     */
    async continueProcess(parsedCard, mode) {
        const guided = mode === 'guided';
        const guider = this.createGuider();
        const client = window.ENGINE_WORKER_CLIENT;

        const characterId = this.getAttribute('character-id');
        const characterNamespace = this.getAttribute('character-namespace');

        if (!characterId || !characterNamespace) {
            console.error('Character ID or namespace is missing.');
            return;
        }

        this.root.querySelector(".wizard-prev-button")?.classList.add("visible");

        // Wire up guider questions from worker → UI → answer back
        /** @param {any} data */
        const onGuiderQuestion = async (data) => {
            const { id, qid, questionType, question, options, defaultValue, currentCard } = data;

            await this.save(currentCard);

            /** @type {{value: any}} */
            let result;
            switch (questionType) {
                case 'askOption':
                    result = await guider.askOption(id, question, options, defaultValue);
                    break;
                case 'askOpen':
                    result = await guider.askOpen(id, question, defaultValue);
                    break;
                case 'askAccept':
                    result = await guider.askAccept(id, question, defaultValue);
                    break;
                case 'askNumber':
                    result = await guider.askNumber(id, question, defaultValue);
                    break;
                case 'askBoolean':
                    result = await guider.askBoolean(id, question, defaultValue);
                    break;
                case 'askList':
                    result = await guider.askList(id, question, options, defaultValue);
                    break;
                case 'askArbitraryList':
                    result = await guider.askArbitraryList(id, question, defaultValue);
                    break;
                case 'askAcceptArbitraryList':
                    result = await guider.askAcceptArbitraryList(id, question, defaultValue);
                    break;
                case 'askImageAsset':
                    result = await guider.askImageAsset(id, question, options, defaultValue);
                    break;
                case 'askAudioAsset':
                    result = await guider.askAudioAsset(id, question, options, defaultValue);
                    break;
                default:
                    result = { value: defaultValue };
            }

            client.sendGuiderAnswer({ qid, value: result.value });
        };

        /** @param {any} data */
        const onComplete = async (data) => {
            data.currentCard.state.automaticWizardInProgress = false;
            data.currentCard.state.guidedWizardInProgress = false;
            data.currentCard.state.automaticWizardCompleted = true;
            data.currentCard.state.guidedWizardCompleted = true;
            await this.save(data.currentCard, true);
            this.endOverlay();
            cleanup();
        };

        const cleanup = () => {
            client.onScriptTypeGuiderQuestion = null;
            client.onCardTypeWizardComplete = null;
        };

        // Store cleanup so disconnectedCallback can call it
        this._wizardCleanup = () => {
            cleanup();
            client.cancelCardTypeGeneration();
        };

        client.onScriptTypeGuiderQuestion = onGuiderQuestion;
        client.onCardTypeWizardComplete = onComplete;

        this.initOverlay();

        try {
            /**
             * @type {import('../../../script-generation/base.js').ScriptTypeGenerator}
             */
            const copiedParsedCardWithoutCode = {
                body: [],
                foot: [],
                imports: [],
                head: [],
                state: parsedCard.state || {},
            };
            await client.continueCardTypeWizard({ currentCard: copiedParsedCardWithoutCode, guided, language: window.DREAMENGINE_LANGUAGE });
        } catch (err) {
            cleanup();
            this.showError(err instanceof Error ? err.message : String(err));
            return;
        }

        // If the element was removed (user clicked Go Back / cancelled), stop here
        if (!this.isConnected) return;

        console.log('CardTypeWizard process complete for character:', characterId);

        this.showDone();
    }

    onPrevButtonClick() {
        this.goingBack = true;
        const client = window.ENGINE_WORKER_CLIENT;
        if (client) {
            client.goBackInCardTypeWizard();
        }
    }

    openOverview() {
        const overview = document.createElement('app-character-overview');
        document.body.appendChild(overview);
    }

    /**
     * @param {string} filename
     * @returns {string}
     */
    getAssetPath(filename) {
        if (!filename) return '';
        const characterId = this.getAttribute('character-id') || '';
        const characterNamespace = this.getAttribute('character-namespace') || '';
        const isSystemNamespace = characterNamespace.startsWith('@');
        const cleanNamespace = isSystemNamespace ? characterNamespace.slice(1) : characterNamespace;
        return `${isSystemNamespace ? '@' : ''}assets/${cleanNamespace}/${characterId}/${filename}`;
    }

    /**
     * @param {string} assetPath
     * @returns {string}
     */
    getAssetSrc(assetPath) {
        if (!assetPath) return '';
        const isSystemAsset = assetPath.startsWith('@');
        return (isSystemAsset ? window.DREAMENGINE_DEFAULT_SCRIPTS_HOME : window.DREAMENGINE_HOME) + '/' + (isSystemAsset ? assetPath.slice(1) : assetPath);
    }

    /**
     * @param {string} assetPath
     * @param {File} file
     * @returns {Promise<void>}
     */
    async uploadAssetFile(assetPath, file) {
        await window.API.uploadFileToDEPath(assetPath, file);
    }

    /**
     * Character-specific phrases highlighted inside guider questions.
     * @returns {string[]}
     */
    getHighlightPhrases() {
        return [
            'strongly physically attractive',
            'moderately physically attractive',
            'slightly physically attractive',
            'non physically attractive',
            'bestial or feral',
            'strongly attractive',
            'moderately attractive',
            'slightly attractive',
            'hostile presences',
            'hostile presence',
            'sworn enemies',
            'sworn enemy',
            'close friendship',
            'close friends',
            'close friend',
            'best friendship',
            'best friends',
            'best friend',
            'good friendship',
            'good friends',
            'good friend',
            'in private',
            'in public',
            'bad impression',
            'good impression',
            'wild creatures',
            'wild creature',
            'physical affection',
            'intimate affection',
            'around friends',
            'around family',
            'acquaintance',
            'acquainted with',
            'antagonistic',
            'antagonist',
            'animals',
            'animal',
            'affectionate',
            'affection',
            'non-romantic',
            'romantic',
            'unfriendly',
            'unpleasant',
            'strangers',
            'stranger',
            'ambiguous',
            'intersex',
            'hostile',
            'friendly',
            'friend',
            'family',
            'females',
            'female',
            'males',
            'male',
            'any gender/sex',
            'sexually',
            'bisexual',
            'pansexual',
            'asexual',
            'sexual',
            'sex',
            'pet',
        ];
    }

    /**
     * Persists the given card. Saves are coalesced: if a save is already running it
     * is allowed to finish uninterrupted, and any calls made in the meantime are
     * queued. Only the most recently requested save is kept in the queue (older
     * queued saves are superseded), and every queued caller resolves once that
     * latest save completes.
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {boolean} completed
     * @returns {Promise<void>}
     */
    save(parsedCard, completed = false) {
        // Always record the latest requested save; only the most recent one matters.
        this._pendingSave = { parsedCard, completed };

        // A save is already in flight: let it finish and it will pick up this latest
        // pending save afterwards. All queued callers share the same promise.
        if (this._saveLoopPromise) {
            return this._saveLoopPromise;
        }

        this._saveLoopPromise = (async () => {
            try {
                while (this._pendingSave) {
                    const { parsedCard, completed } = this._pendingSave;
                    this._pendingSave = null;
                    await this._performSave(parsedCard, completed);
                }
            } finally {
                this._saveLoopPromise = null;
            }
        })();

        return this._saveLoopPromise;
    }

    /**
     * Performs a single save operation and updates the autosave indicator.
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {boolean} completed
     */
    async _performSave(parsedCard, completed) {
        this.saving = true;
        this.lastSavedCard = parsedCard;
        const jsContent = getJsScriptFromGenerator(parsedCard, undefined, undefined, completed ? [] : ["initialize"]);
        const characterId = this.getAttribute('character-id') || "";
        const characterNamespace = this.getAttribute('character-namespace') || "";
        this.showAutosaveStatus();
        await window.API.updateScriptFile(
            characterNamespace,
            characterId,
            jsContent
        );
        this.hideAutosaveStatus();
        this.saving = false;
    }
}

customElements.define('app-cardtype-wizard', CardTypeWizard);
