import { getJsScriptFromGenerator, isScriptTypeGeneratorFile, parseScriptGeneratorFrom } from '../../../script-generation/base.js';
import { playCancelSound, playHoverSound, setTempSoundDisable, stopAllAmbiencesAndStartNewOne } from '../../sound.js';
import { CardTypeWizard } from './character-wizard.js';

export class WorldWizard extends CardTypeWizard {
    async connectedCallback() {
        this.render();

        document.addEventListener('keydown', this.onDocumentKeydown);

        this.root.getElementById('cancel-btn')?.addEventListener('click', () => {
            playCancelSound();
            setTempSoundDisable();
            this.remove();
        });

        this.root.querySelectorAll('.wizard-buttons div').forEach(btn => {
            btn.addEventListener('mouseenter', playHoverSound);
        });

        this.initializeWorldWizard();

        await stopAllAmbiencesAndStartNewOne([{ src: './sounds/dream-world.mp3', volume: 3 }], 1000, 1000);
    }

    async initializeWorldWizard() {
        const worldId = this.getAttribute('world-id');
        const worldNamespace = this.getAttribute('world-namespace');
        if (!worldId || !worldNamespace) {
            console.error('WorldWizard requires world-id and world-namespace attributes');
            return;
        }

        /** @type {{src: string}} */
        let worldSource;
        try {
            worldSource = await window.ENGINE_WORKER_CLIENT.getRawScriptSource({ namespace: worldNamespace, id: worldId });
        } catch (err) {
            this.showError(err instanceof Error ? err.message : String(err));
            return;
        }
        const isCardType = isScriptTypeGeneratorFile(worldSource.src);

        if (!isCardType) {
            const contentArea = this.root.querySelector('.wizard-content');
            // @ts-ignore
            contentArea.innerHTML = `<p>This world script was not generated by the world wizard, so it can only be edited manually.</p>`;
        } else {
            const parsedCard = parseScriptGeneratorFrom(worldSource.src);
            const isCompleteCard = parsedCard.state.guidedWizardCompleted;
            if (isCompleteCard) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This world script has already been completed using the wizard</p>`;
                return;
            }

            if (parsedCard.state.version && parsedCard.state.version !== 2) {
                const contentArea = this.root.querySelector('.wizard-content');
                // @ts-ignore
                contentArea.innerHTML = `<p>This world script was generated with version ${parsedCard.state.version} of the wizard, but you are currently running version 2. There may be incompatibilities that prevent the wizard from working correctly. Please update your world script by copying its content, creating a new world with the latest version of the wizard, and pasting the content into the new world's script.</p>`;
                return;
            }

            let isGuidedInProgress = parsedCard.state.guidedWizardInProgress && !parsedCard.state.guidedWizardCompleted;

            const isNewFile = worldSource.src.startsWith("//@placeholder");

            if (isGuidedInProgress || isNewFile) {
                const titleName = 'World Builder';
                const titleText = this.root.querySelector('.wizard-title span:first-child');
                if (titleText) {
                    titleText.textContent = titleName;
                }

                this.startMode(parsedCard, 'guided', isNewFile);
            } else {
                const contentArea = this.root.querySelector('.wizard-content');
                // unknown state, should not happen, say that it's probably another version of the wizard and not this one
                // @ts-ignore
                contentArea.innerHTML = `<p>This world script is in an unknown state. It may have been generated by an older/newer version of the wizard, or there may be an issue with the script. Please edit the script manually or try regenerating it with the latest version of the wizard.</p>`;
            }
        }
    }

    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard
     * @param {"guided"} mode
     * @param {boolean} isNewFile
     */
    startMode(parsedCard, mode, isNewFile) {
        if (isNewFile) {
            // this.markUnsaved();
            // parsedCard.state.guidedWizardInProgress = true;
            // parsedCard.state.guidedWizardCompleted = false;
            this.continueProcess(parsedCard, mode);
        } else {
            this.continueProcess(parsedCard, mode);
        }
    }

    /**
     * @param {import('../../../script-generation/base.js').ScriptTypeGenerator} parsedCard 
     * @param {"guided"} mode
     */
    async continueProcess(parsedCard, mode) {
        const guided = mode === 'guided';
        const guider = this.createGuider(parsedCard, guided);
        const client = window.ENGINE_WORKER_CLIENT;

        const worldId = this.getAttribute('world-id');
        const worldNamespace = this.getAttribute('world-namespace');

        if (!worldId || !worldNamespace) {
            console.error('World ID or namespace is missing.');
            return;
        }


        // Wire up guider questions from worker → UI → answer back
        /** @param {any} data */
        const onGuiderQuestion = async (data) => {
            if (!guider) return;
            const { id, qid, questionType, question, options, defaultValue } = data;
            /** @type {{value: any}} */
            let result;
            switch (questionType) {
                case 'askOption':
                    result = await guider.askOption(id, question, options, defaultValue);
                    break;
                case 'askOpen':
                    result = await guider.askOpen(id, question, defaultValue);
                    break;
                case 'askAccept':
                    result = await guider.askAccept(id, question, defaultValue);
                    break;
                case 'askNumber':
                    result = await guider.askNumber(id, question, defaultValue);
                    break;
                case 'askBoolean':
                    result = await guider.askBoolean(id, question, defaultValue);
                    break;
                case 'askList':
                    result = await guider.askList(id, question, options, defaultValue);
                    break;
                case 'askArbitraryList':
                    result = await guider.askArbitraryList(id, question, defaultValue);
                    break;
                case 'askAcceptArbitraryList':
                    result = await guider.askAcceptArbitraryList(id, question, defaultValue);
                    break;
                default:
                    result = { value: defaultValue };
            }
            client.sendGuiderAnswer({ qid, value: result.value });
        };

        let lastCard = parsedCard;

        // Wire up autosave from worker → save file → ack back
        /** @param {any} data */
        const onAutosave = async (data) => {
            const { sid, currentCard } = data;
            const jsContent = getJsScriptFromGenerator(currentCard);
            this.showAutosaveStatus();
            lastCard = currentCard;
            try {
                await window.API.updateScriptFile(
                    worldNamespace,
                    worldId,
                    jsContent
                );
            } catch (err) {
                cleanup();
                client.cancelCardTypeGeneration();
                this.showError(err instanceof Error ? err.message : String(err));
                return;
            }
            this.hideAutosaveStatus();
            client.sendAutosaveAck({ sid });
        };

        /** @param {any} data */
        const onComplete = (data) => {
            this.endOverlay();
            cleanup();
        };

        const cleanup = () => {
            client.onScriptTypeGuiderQuestion = null;
            client.onCardTypeAutosave = null;
            client.onCardTypeWizardComplete = null;
        };

        // Store cleanup so disconnectedCallback can call it
        this._wizardCleanup = () => {
            cleanup();
            client.cancelCardTypeGeneration();
        };

        client.onScriptTypeGuiderQuestion = onGuiderQuestion;
        client.onCardTypeAutosave = onAutosave;
        client.onCardTypeWizardComplete = onComplete;

        // this.initOverlay();

        // try {
        //     //await client.continueCardTypeWizard({ currentCard: parsedCard, guided });
        // } catch (err) {
        //     cleanup();
        //     this.showError(err instanceof Error ? err.message : String(err));
        //     return;
        // }

        // If the element was removed (user clicked Go Back / cancelled), stop here
        // if (!this.isConnected) return;

        // console.log('WorldWizard process complete for world:', worldId);

        // lastCard.config.guidedWizardInProgress = false;
        // lastCard.config.guidedWizardCompleted = true;
        // const finalJsContent = getJsCard(lastCard);
        // try {
        //     await window.API.updateScriptFile(
        //         worldNamespace,
        //         worldId,
        //         finalJsContent,
        //     );
        // } catch (err) {
        //     cleanup();
        //     this.showError(err instanceof Error ? err.message : String(err));
        //     return;
        // }

        // this.showDone();
    }

    render() {
        this.root.innerHTML = `
      <style>
        @import "./components/wizard/wizard.css";
      </style>
      <div class="wizard-overlay">
        <div class="wizard-title">
            <span>World Builder</span>
            <span class="wizard-autosave"></span>
        </div>
        <div class="wizard-content">
            <slot></slot>
        </div>
        <div class="wizard-buttons">
            <div id="cancel-btn">Go Back</div>
        </div>
      </div>
    `;
    }
}

customElements.define('app-world-wizard', WorldWizard);
