interface FunctionTypes {
user_name(DE: DEObject, char: CompleteCharacterReference, ): string;
char(DE: DEObject, char: CompleteCharacterReference, ): string;
char_is_male(DE: DEObject, char: CompleteCharacterReference, ): boolean;
char_is_female(DE: DEObject, char: CompleteCharacterReference, ): boolean;
char_is_ambiguous(DE: DEObject, char: CompleteCharacterReference, ): boolean;
char_sex_is_male(DE: DEObject, char: CompleteCharacterReference, ): boolean;
char_sex_is_female(DE: DEObject, char: CompleteCharacterReference, ): boolean;
char_sex_is_intersex(DE: DEObject, char: CompleteCharacterReference, ): boolean;
all_world_characters(DE: DEObject, char: CompleteCharacterReference, ): string[];
all_world_characters_but_user(DE: DEObject, char: CompleteCharacterReference, ): string[];
current_location(DE: DEObject, char: CompleteCharacterReference, ): string;
current_location_is_in_vehicle(DE: DEObject, char: CompleteCharacterReference, ): boolean;
current_location_is_safe(DE: DEObject, char: CompleteCharacterReference, ): boolean;
all_characters_at_location(DE: DEObject, char: CompleteCharacterReference, location_name:string): string[];
location_is_vehicle(DE: DEObject, char: CompleteCharacterReference, location_name:string): boolean;
location_is_safe(DE: DEObject, char: CompleteCharacterReference, location_name:string): boolean;
get_last_state_causants(DE: DEObject, char: CompleteCharacterReference, state_name:string): string[];
get_last_state_cause(DE: DEObject, char: CompleteCharacterReference, state_name:string): string[];
get_last_state_character_causants(DE: DEObject, char: CompleteCharacterReference, state_name:string): string[];
get_last_state_object_causants(DE: DEObject, char: CompleteCharacterReference, state_name:string): string[];
get_states(DE: DEObject, char: CompleteCharacterReference, ): string[];
has_state(DE: DEObject, char: CompleteCharacterReference, state_name:string): boolean;
state_has_just_activated(DE: DEObject, char: CompleteCharacterReference, state_name:string): boolean;
get_state_activation_cycles_ago(DE: DEObject, char: CompleteCharacterReference, state_name:string): number;
get_social_group(DE: DEObject, char: CompleteCharacterReference, min_bond_level:number, max_bond_level:number, min_2_bond_level:number, max_2_bond_level:number): string[];
get_present_social_group(DE: DEObject, char: CompleteCharacterReference, min_bond_level:number, max_bond_level:number, min_2_bond_level:number, max_2_bond_level:number): string[];
get_present_conversing_social_group(DE: DEObject, char: CompleteCharacterReference, min_bond_level:number, max_bond_level:number, min_2_bond_level:number, max_2_bond_level:number): string[];
get_difference_of_present_social_group(DE: DEObject, char: CompleteCharacterReference, list:string[]): string[];
get_ex_social_group(DE: DEObject, char: CompleteCharacterReference, min_bond_level:number, max_bond_level:number, min_2_bond_level:number, max_2_bond_level:number): string[];
is_dead(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_male(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_female(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_ambiguous(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_sex_male(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_sex_female(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_sex_intersex(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_char(DE: DEObject, char: CompleteCharacterReference, potential_character:string): boolean;
is_user(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_present_member(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_not_present(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_gone(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_in_conversation(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_standing(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_sitting(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_laying_down(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
last_saw(DE: DEObject, char: CompleteCharacterReference, character:string): string;
has_no_idea_where_is(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
does_not_know(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_strangers_with(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_at_same_location(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_at_same_slot(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
is_here(DE: DEObject, char: CompleteCharacterReference, character:string): boolean;
intersect(DE: DEObject, char: CompleteCharacterReference, list1:string[], list2:string[]): string[];
union(DE: DEObject, char: CompleteCharacterReference, list1:string[], list2:string[]): string[];
difference(DE: DEObject, char: CompleteCharacterReference, list1:string[], list2:string[]): string[];
format_and(DE: DEObject, char: CompleteCharacterReference, list:string[]): string;
format_or(DE: DEObject, char: CompleteCharacterReference, list:string[]): string;
length(DE: DEObject, char: CompleteCharacterReference, list:any[]): number;
in(DE: DEObject, char: CompleteCharacterReference, value:any, list:any[]): boolean;
gt(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
lt(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
eq(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
neq(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
lte(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
gte(DE: DEObject, char: CompleteCharacterReference, value1:number, value2:number): boolean;
format_verb_to_be(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
format_plural_or_singular(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[], plural, singular): string;
format_object_pronoun(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
format_possessive(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
format_reflexive(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
format_pronoun(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
format_ownership_pronoun(DE: DEObject, char: CompleteCharacterReference, list_or_character:string|string[]): string;
get_random_seed_from_string(DE: DEObject, char: CompleteCharacterReference, options_number:number, input_string:string): number;
}
