// Auto-generated by map-local-types.js — do not edit manually.
// Regenerate with: node js/util/map-local-types.js
//
// This file extends DEScriptRegistry (declared in DE.d.ts) via declaration merging
// so that importScript() calls return the correct types for known scripts.

declare interface DEScriptRegistry {
    "bond-systems/full-standard-bond-system": DEScript & {
        setupManually(character: DECompleteCharacterReference, options: FSSOptions): void;
    };
    "bond-systems/sfw-simplified-standard": DEScript;
    "characters/dema-basic": DEScript;
    "testing/states": DEScript;
    "worlds/simple-lunar-station": DEScript;
}
