// Auto-generated by map-local-types.js — do not edit manually.
// Regenerate with: node js/util/map-local-types.js
//
// This file extends DEScriptRegistry (declared in DE.d.ts) via declaration merging
// so that importScript() calls return the correct types for known scripts.

declare type FSSBase = { description: DEStringTemplateCharAndOther; relationshipName: DEStringTemplateCharAndOther | null; bondAdditionalDescription?: DEStringTemplateCharAndOther | undefined; generalCharacterDescriptionInjection?: DEStringTemplateCharAndOther | undefined; generalCharacterDescriptionInjectionEx?: DEStringTemplateCharAndOther | undefined; openToAffection: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ value: "not" | "slight" | "moderate" | "very"; reason?: string | null; }>; openToIntimateAffection: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ value: "not" | "slight" | "moderate" | "very"; reason?: string | null; }>; openToSex: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ value: "not" | "slight" | "moderate" | "very"; reason?: string | null; }>; proneToInitiatingAffection: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ probability: number; options?: string[]; }>; proneToInitiatingIntimateAffection: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ probability: number; options?: string[]; }>; proneToInitiatingSex: (DE: DEObject, char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<{ probability: number; options?: string[]; }>; };
declare type FSSByFamilyTie = { family: FSSBase; nonFamily: FSSBase; };
declare type FSSLoveDefinition = { deepInLove_50_100: FSSByFamilyTie; strongRomanticInterest_35_50: FSSByFamilyTie; romanticInterest_20_35: FSSByFamilyTie; slightRomanticInterest_10_20: FSSByFamilyTie; noRomanticInterest_0_10: FSSByFamilyTie; };
declare type FSSCreepyLoveDefinition = { sexualAbuseInterest_50_100: FSSByFamilyTie; stalkingInterest_35_50: FSSByFamilyTie; obsessiveInterest_20_35: FSSByFamilyTie; creepyInterest_10_20: FSSByFamilyTie; noRomance_0_10: FSSByFamilyTie; };
declare type FSS4DOptions = { type: "4d_standard"; familyCreepy: boolean; bondChangeFineTune?: number | undefined; bondChangeNegativityBias?: number | undefined; strangerBreakawayBondWeightAbsolute?: number | undefined; strangerBreakawayInteractionsCount?: number | undefined; strangerBreakawayTimeMinutes?: number | undefined; strangerNegativeMultiplier?: number | undefined; strangerPositiveMultiplier?: number | undefined; neutralInteractionBondChange?: number | undefined; foe_n100_n50: FSSLoveDefinition; hostile_n50_n35: FSSLoveDefinition; antagonistic_n35_n20: FSSLoveDefinition; unfriendly_n20_n10: FSSLoveDefinition; unpleasant_n10_0: FSSLoveDefinition; acquaintance_0_10: FSSLoveDefinition; friendly_10_20: FSSLoveDefinition; goodFriend_20_35: FSSLoveDefinition; closeFriend_35_50: FSSLoveDefinition; bestFriend_50_100: FSSLoveDefinition; strangerBad_n100_n5: FSSBase; strangerNeutral_n5_5: FSSBase; strangerGood_5_100: FSSBase; };
declare type FSS4DCreepyOptions = { type: "4d_creepy"; bondChangeFineTune?: number | undefined; bondChangeNegativityBias?: number | undefined; strangerBreakawayBondWeightAbsolute?: number | undefined; strangerBreakawayInteractionsCount?: number | undefined; strangerBreakawayTimeMinutes?: number | undefined; strangerNegativeMultiplier?: number | undefined; strangerPositiveMultiplier?: number | undefined; neutralInteractionBondChange?: number | undefined; foe_n100_n50: FSSCreepyLoveDefinition; hostile_n50_n35: FSSCreepyLoveDefinition; antagonistic_n35_n20: FSSCreepyLoveDefinition; unfriendly_n20_n10: FSSCreepyLoveDefinition; unpleasant_n10_0: FSSCreepyLoveDefinition; acquaintance_0_10: FSSCreepyLoveDefinition; friendly_10_20: FSSCreepyLoveDefinition; goodFriend_20_35: FSSCreepyLoveDefinition; closeFriend_35_50: FSSCreepyLoveDefinition; bestFriend_50_100: FSSCreepyLoveDefinition; strangerBad_n100_n5: FSSBase; strangerNeutral_n5_5: FSSBase; strangerGood_5_100: FSSBase; };

declare interface DEScriptRegistry {
    "@bond-systems/basic-bond-questions": DEScript & {
        name: string;
        addBasicBondQuestions(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems/deteriorating-bonds": DEScript & {
        name: string;
    };
    "@bond-systems/full-standard-bond-system": DEScript & {
        setup(DE: DEObject, character: DECompleteCharacterReference, options: FSS4DOptions | FSS4DCreepyOptions): DECompleteCharacterReference;
    };
    "@characters/dema-basic": DEScript;
    "@worlds/simple-lunar-station": DEScript;
}
