// Auto-generated by map-local-types.js — do not edit manually.
// Regenerate with: node js/util/map-local-types.js
//
// This file extends DEScriptRegistry (declared in DE.d.ts) via declaration merging
// so that importScript() calls return the correct types for known scripts.

declare type FSSBase = { description: DEStringTemplateCharAndOther; relationshipName: DEStringTemplateCharAndOther; bondAdditionalDescription?: DEStringTemplateCharAndOther | undefined; generalCharacterDescriptionInjection?: DEStringTemplateCharAndOther | undefined; generalCharacterDescriptionInjectionEx?: DEStringTemplateCharAndOther | undefined; openToAffection: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<DEOpenToIntimacyResponse>; openToIntimateAffection: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<DEOpenToIntimacyResponse>; openToSex: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<DEOpenToIntimacyResponse>; proneToInitiatingAffection: { probability: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<number>; actions: DEIntimateAction[]; }; proneToInitiatingIntimateAffection: { probability: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<number>; actions: DEIntimateAction[]; }; proneToInitiatingSex: { probability: (char: DECompleteCharacterReference, other: DECompleteCharacterReference) => PromiseOrNot<number>; actions: DEIntimateAction[]; }; openToAffectionResponses: Array<DEIntimateOpenActivity>; openToIntimateAffectionResponses: Array<DEIntimateOpenActivity>; openToSexResponses: Array<DEIntimateOpenActivity>; };
declare type FSSByFamilyTie = { family?: FSSBase | undefined; nonFamily?: FSSBase | undefined; };
declare type FSSLoveDefinition = { deepInLove_50_100?: FSSByFamilyTie | undefined; strongRomanticInterest_35_50?: FSSByFamilyTie | undefined; romanticInterest_20_35?: FSSByFamilyTie | undefined; slightRomanticInterest_10_20?: FSSByFamilyTie | undefined; noRomanticInterest_0_10: FSSByFamilyTie; };
declare type FSSLoveDefinitionNoFamily = { deepInLove_50_100?: FSSBase | undefined; strongRomanticInterest_35_50?: FSSBase | undefined; romanticInterest_20_35?: FSSBase | undefined; slightRomanticInterest_10_20?: FSSBase | undefined; noRomanticInterest_0_10: FSSBase; };
declare type FSSCreepyLoveDefinition = { sexualAbuseInterest_50_100?: FSSByFamilyTie | undefined; stalkingInterest_35_50?: FSSByFamilyTie | undefined; obsessiveInterest_20_35?: FSSByFamilyTie | undefined; creepyInterest_10_20?: FSSByFamilyTie | undefined; noRomance_0_10: FSSByFamilyTie; };
declare type FSSCreepyLoveDefinitionNoFamily = { sexualAbuseInterest_50_100?: FSSBase | undefined; stalkingInterest_35_50?: FSSBase | undefined; obsessiveInterest_20_35?: FSSBase | undefined; creepyInterest_10_20?: FSSBase | undefined; noRomance_0_10: FSSBase; };
declare type FSS4DOptions = { type: "4d_standard"; familyCreepy: boolean; bondChangeFineTune?: number | undefined; bondChangeNegativityBias?: number | undefined; strangerBreakawayBondWeightAbsolute?: number | undefined; strangerBreakawayInteractionsCount?: number | undefined; strangerBreakawayTimeMinutes?: number | undefined; strangerNegativeMultiplier?: number | undefined; strangerPositiveMultiplier?: number | undefined; neutralInteractionBondChange?: number | undefined; foe_n100_n50: FSSLoveDefinition; hostile_n50_n35: FSSLoveDefinition; antagonistic_n35_n20: FSSLoveDefinition; unfriendly_n20_n10: FSSLoveDefinition; unpleasant_n10_0: FSSLoveDefinition; acquaintance_0_10: FSSLoveDefinition; friendly_10_20: FSSLoveDefinition; goodFriend_20_35: FSSLoveDefinition; closeFriend_35_50: FSSLoveDefinition; bestFriend_50_100: FSSLoveDefinition; strangerBad_n100_n5: FSSLoveDefinitionNoFamily; strangerNeutral_n5_5: FSSLoveDefinitionNoFamily; strangerGood_5_100: FSSLoveDefinitionNoFamily; };
declare type FSS4DCreepyOptions = { type: "4d_creepy"; bondChangeFineTune?: number | undefined; bondChangeNegativityBias?: number | undefined; strangerBreakawayBondWeightAbsolute?: number | undefined; strangerBreakawayInteractionsCount?: number | undefined; strangerBreakawayTimeMinutes?: number | undefined; strangerNegativeMultiplier?: number | undefined; strangerPositiveMultiplier?: number | undefined; neutralInteractionBondChange?: number | undefined; foe_n100_n50: FSSCreepyLoveDefinition; hostile_n50_n35: FSSCreepyLoveDefinition; antagonistic_n35_n20: FSSCreepyLoveDefinition; unfriendly_n20_n10: FSSCreepyLoveDefinition; unpleasant_n10_0: FSSCreepyLoveDefinition; acquaintance_0_10: FSSCreepyLoveDefinition; friendly_10_20: FSSCreepyLoveDefinition; goodFriend_20_35: FSSCreepyLoveDefinition; closeFriend_35_50: FSSCreepyLoveDefinition; bestFriend_50_100: FSSCreepyLoveDefinition; strangerBad_n100_n5: FSSCreepyLoveDefinitionNoFamily; strangerNeutral_n5_5: FSSCreepyLoveDefinitionNoFamily; strangerGood_5_100: FSSCreepyLoveDefinitionNoFamily; };
declare type CharacterScriptMetadataFields = { __name: string; age: number; gender: "male" | "female" | "ambiguous"; sex: "male" | "female" | "intersex" | "none"; species: string; speciesType: "humanoid" | "feral" | "animal"; height: number; weight: number; };
declare type CharacterScriptMetadata = CharacterScriptMetadataFields & Record<string, string | number | boolean | undefined>;

declare interface DEScriptRegistry {
    "@bond-systems/basic-bond-questions": DEScript & {
        name: string;
        addBasicBondQuestions(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems/deteriorating-bonds": DEScript & {
        name: string;
    };
    "@bond-systems/full-standard-bond-system": DEScript & {
        language: string;
        setup(DE: DEObject, character: DECompleteCharacterReference, options: FSS4DOptions | FSS4DCreepyOptions): DECompleteCharacterReference;
    };
    "@bond-systems-preset/aromantic": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/asexual": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/basic": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/caretaker": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/codependent": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/dandere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/deredere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/flirtatious": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/himedere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/kuudere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/rivalrous": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/tsundere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@bond-systems-preset/yandere": DEScript & {
        name: string;
        applyToCharacter(DE: DEObject, character: DECompleteCharacterReference): void;
    };
    "@characters/dema-basic": DEScript & {
        language: string;
        metadata: CharacterScriptMetadata;
    };
    "@std/deapp": DEScript & {
        language: string;
        buildCharacterScriptMetadata(metadata: CharacterScriptMetadata): CharacterScriptMetadata;
    };
    "@worlds/simple-lunar-station": DEScript & {
        language: string;
        metadata: { intro: { title: string; subtitle: string; }[]; };
    };
}
